<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class AgencyProductList {
  public static function register(): void { add_shortcode('avanik_my_products',[self::class,'render']); add_action('admin_post_avanik_product_delete',[self::class,'delete']); add_action('admin_post_avanik_product_submit',[self::class,'submit']); }
  public static function render(): string { if(!is_user_logged_in()) return '<p>ابتدا وارد شوید.</p>'; $u=wp_get_current_user(); if(!AgencyOnboarding::can_sell($u->ID)) return '<p>حساب شما هنوز تأیید نشده است.</p>'; $rows=ProductRepository::for_supplier($u->ID); ob_start(); ?>
  <section dir="rtl"><h2>محصولات من</h2><table><thead><tr><th>عنوان</th><th>نوع</th><th>قیمت</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?php echo esc_html($r['title']); ?></td><td><?php echo esc_html($r['type']); ?></td><td><?php echo esc_html($r['price'].' '.$r['currency']); ?></td><td><?php echo esc_html($r['status']); ?></td><td><?php if(in_array($r['status'],[Product::DRAFT,Product::REJECTED],true)): ?><form style="display:inline" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('avanik_product_submit'); ?><input type="hidden" name="action" value="avanik_product_submit"><input type="hidden" name="product_id" value="<?php echo esc_attr($r['id']); ?>"><button>ارسال برای بررسی</button></form><?php endif; if($r['status']===Product::DRAFT): ?><form style="display:inline" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('avanik_product_delete'); ?><input type="hidden" name="action" value="avanik_product_delete"><input type="hidden" name="product_id" value="<?php echo esc_attr($r['id']); ?>"><button>حذف</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></section>
  <?php return (string)ob_get_clean(); }
  public static function submit(): void { if(!is_user_logged_in()||!check_admin_referer('avanik_product_submit')) wp_die('Unauthorized'); $u=wp_get_current_user(); if(AgencyOnboarding::can_sell($u->ID)) ProductRepository::submit_for_review((int)($_POST['product_id']??0),$u->ID); wp_safe_redirect(wp_get_referer()?:home_url('/')); exit; }
  public static function delete(): void { if(!is_user_logged_in()||!check_admin_referer('avanik_product_delete')) wp_die('Unauthorized'); $u=wp_get_current_user(); if(AgencyOnboarding::can_sell($u->ID)) ProductRepository::delete_owned((int)($_POST['product_id']??0),$u->ID); wp_safe_redirect(wp_get_referer()?:home_url('/')); exit; }
}