<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class BookingPassengers {
 public static function table_name(): string { global $wpdb; return $wpdb->prefix.'avanik_booking_passengers'; }
 public static function install(): void { global $wpdb; $t=self::table_name(); $c=$wpdb->get_charset_collate(); require_once ABSPATH.'wp-admin/includes/upgrade.php'; dbDelta("CREATE TABLE {$t} (id bigint unsigned NOT NULL AUTO_INCREMENT, booking_id varchar(64) NOT NULL, first_name varchar(100) NOT NULL, last_name varchar(100) NOT NULL, phone varchar(40) DEFAULT '', email varchar(190) DEFAULT '', national_id text NULL, nationality varchar(100) DEFAULT '', date_of_birth date DEFAULT NULL, passport_no text NULL, passport_expiry date DEFAULT NULL, gender varchar(30) DEFAULT '', passenger_type varchar(30) NOT NULL DEFAULT 'adult', custom_data longtext NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY(id), KEY booking_id(booking_id)) {$c};"); }
 public static function for_booking(string $booking_id): array { global $wpdb; $rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table_name().' WHERE booking_id=%s ORDER BY id ASC',$booking_id),ARRAY_A)?:[]; foreach($rows as &$r){$r['national_id']=PassengerDataSecurity::decrypt((string)$r['national_id']);$r['passport_no']=PassengerDataSecurity::decrypt((string)$r['passport_no']);$r['custom_data']=self::decrypt_custom($r['custom_data']);} return $rows; }
 public static function add(string $booking_id,array $data): int { global $wpdb; $now=current_time('mysql'); $custom=(array)($data['custom_data']??[]); $ok=$wpdb->insert(self::table_name(),['booking_id'=>$booking_id,'first_name'=>sanitize_text_field($data['first_name']??''),'last_name'=>sanitize_text_field($data['last_name']??''),'phone'=>sanitize_text_field($data['phone']??''),'email'=>sanitize_email($data['email']??''),'national_id'=>PassengerDataSecurity::encrypt(sanitize_text_field($data['national_id']??'')),'nationality'=>sanitize_text_field($data['nationality']??''),'date_of_birth'=>self::date_or_null($data['date_of_birth']??''),'passport_no'=>PassengerDataSecurity::encrypt(sanitize_text_field($data['passport_no']??'')),'passport_expiry'=>self::date_or_null($data['passport_expiry']??''),'gender'=>sanitize_key($data['gender']??''),'passenger_type'=>sanitize_key($data['passenger_type']??'adult'),'custom_data'=>self::encrypt_custom($custom),'created_at'=>$now,'updated_at'=>$now]); return $ok?(int)$wpdb->insert_id:0; }
 private static function encrypt_custom(array $data): string { $out=[]; foreach($data as $k=>$v){$k=sanitize_key($k);$out[$k]=PassengerDataSecurity::encrypt(sanitize_text_field((string)$v));} return wp_json_encode($out); }
 private static function decrypt_custom($json): array { $data=json_decode((string)$json,true)?:[]; foreach($data as $k=>$v)$data[$k]=PassengerDataSecurity::decrypt((string)$v); return $data; }
 private static function date_or_null(string $value): ?string { $value=sanitize_text_field($value); if(!$value)return null; $d=\DateTime::createFromFormat('Y-m-d',$value); return $d&&$d->format('Y-m-d')===$value?$value:null; }
}