<?php
namespace Avanik;
if (!defined('ABSPATH')) exit;
final class ElementorIntegration {
 public static function boot(): void {add_action('elementor/editor/after_enqueue_scripts',[self::class,'editor_assets']);add_action('elementor/frontend/after_enqueue_scripts',[self::class,'frontend_assets']);add_action('init',[self::class,'register_shortcodes']);}
 public static function register_shortcodes(): void {foreach(['search','hero','services','destinations','why','login'] as $x)add_shortcode('avanik_'.$x,[self::class,'shortcode_'.$x]);}
 public static function editor_assets(): void {self::enqueue_shared();} public static function frontend_assets(): void {self::enqueue_shared();}
 private static function enqueue_shared(): void {if(!wp_style_is('avanik-ui-v042','enqueued'))wp_enqueue_style('avanik-ui-v042',AVANIK_URI.'/assets/css/avanik-ui-v042.css',['avanik-style'],AVANIK_VERSION);if(!wp_script_is('avanik-ui-v042','enqueued'))wp_enqueue_script('avanik-ui-v042',AVANIK_URI.'/assets/js/avanik-ui-v042.js',[],AVANIK_VERSION,true);if(!wp_script_is('avanik-elementor-builder','enqueued'))wp_enqueue_script('avanik-elementor-builder',AVANIK_URI.'/assets/js/avanik-elementor-builder.js',['avanik-ui-v042'],AVANIK_VERSION,true);wp_localize_script('avanik-elementor-builder','AvanikData',['ajaxUrl'=>admin_url('admin-ajax.php'),'home'=>home_url('/')]);}
 public static function shortcode_hero($atts=[]): string {$a=shortcode_atts(['title'=>'','accent'=>'','eyebrow'=>'','subtitle'=>''],$atts);$ey=$a['eyebrow']?:avanik_option('hero_eyebrow','سفر بعدی شما از اینجا شروع می‌شود');$title=$a['title']?:avanik_option('hero_title_prefix','پرواز به');$accent=$a['accent']?:avanik_option('hero_title_accent','استانبول');$sub=$a['subtitle']?:avanik_option('hero_subtitle','با بهترین قیمت و خدمات ویژه');$bg=avanik_option('hero',AVANIK_URI.'/assets/images/hero-reference-istanbul.jpg');return '<section class="avanik-hero" style="--avanik-hero-image:url(\''.esc_url($bg).'\')"><div class="avanik-hero-bg"></div><div class="avanik-hero-wash"></div><div class="avanik-shell avanik-hero-content"><div class="avanik-hero-copy"><div class="avanik-eyebrow">'.esc_html($ey).'</div><h1>'.esc_html($title).' <strong>'.esc_html($accent).'</strong></h1><p>'.esc_html($sub).'</p></div></div></section>';}
 public static function shortcode_search($atts=[]): string {$a=shortcode_atts(['compact'=>''],$atts);ob_start();?><section class="avanik-search-card <?php echo $a['compact']==='yes'?'avanik-search-card--compact':''; ?>"><div class="avanik-shell"><div class="avanik-search-tabs" role="tablist"><button class="active" type="button" data-service="domestic-flight">✈ پرواز داخلی</button><button type="button" data-service="foreign-flight">✈ پرواز خارجی</button><button type="button" data-service="domestic-tour">▣ تور داخلی</button><button type="button" data-service="foreign-tour">▣ تور خارجی</button><button type="button" data-service="hotel">▤ هتل</button></div><form class="avanik-search-form" onsubmit="return AvanikSearch.submit(event)"><?php echo self::city_field('origin','مبدا','tehran','تهران (همه فرودگاه‌ها)');?><button class="avanik-swap-btn" type="button" aria-label="جابجایی مبدا و مقصد">↔</button><?php echo self::city_field('destination','مقصد','mashhad','مشهد');echo self::date_field('departure','تاریخ رفت');echo self::date_field('return','تاریخ برگشت');?><div class="avanik-passenger-field avanik-field"><span>مسافر</span><button type="button" class="avanik-passenger-trigger" aria-expanded="false"><span>♙ <b class="avanik-passenger-total">۱ مسافر</b></span><b>⌄</b></button><div class="avanik-passenger-popover" aria-hidden="true"><?php echo self::passenger_row('adult','بزرگسال','۱۲ سال به بالا',1),self::passenger_row('child','کودک','۲ تا ۱۱ سال',0),self::passenger_row('infant','نوزاد','زیر ۲ سال',0);?><button type="button" class="avanik-passenger-done">تأیید</button></div></div><button class="avanik-search-btn" type="submit"><span>جستجو</span>⌕</button></form></div></section><?php return ob_get_clean();}
 private static function city_field($k,$title,$value,$label): string{return '<label class="avanik-field avanik-field--location" data-city-field="'.esc_attr($k).'"><span>'.esc_html($title).'</span><div class="avanik-input-wrap"><button class="avanik-city-trigger" type="button" data-city-trigger="'.esc_attr($k).'"><span data-city-label="'.esc_attr($k).'">'.esc_html($label).'</span><span>⌄</span></button></div><input type="hidden" value="'.esc_attr($value).'" data-city-value="'.esc_attr($k).'"><div class="avanik-city-menu"></div></label>';}
 private static function date_field($k,$title): string{return '<label class="avanik-field avanik-field--date"><span>'.esc_html($title).'</span><div class="avanik-input-wrap"><button class="avanik-date-trigger" type="button" data-date-open="'.esc_attr($k).'"><span data-date-label="'.esc_attr($k).'">امروز</span><span>⌄</span></button></div><input type="hidden" data-date-value="'.esc_attr($k).'" /></label>';}
 private static function passenger_row($k,$title,$sub,$count): string{return '<div class="avanik-passenger-row"><div><strong>'.esc_html($title).'</strong><small>'.esc_html($sub).'</small></div><div class="avanik-stepper"><button type="button" data-pass="'.esc_attr($k).'" data-step="-1">−</button><b id="'.esc_attr($k).'-count">'.esc_html($count).'</b><button type="button" data-pass="'.esc_attr($k).'" data-step="1">+</button></div></div>';}
 public static function shortcode_services(): string{return '<section class="avanik-section avanik-services"><div class="avanik-shell"><div class="avanik-section-title"><h2>خدمات ما</h2></div></div></section>';}
 public static function shortcode_destinations(): string{return '<section class="avanik-section avanik-destinations"><div class="avanik-shell"><div class="avanik-section-title"><h2>مقصدهای محبوب</h2></div></div></section>';}
 public static function shortcode_why(): string{return '<section class="avanik-why"><div class="avanik-shell"><div class="avanik-section-title light"><h2>چرا آوانیک پرواز آسیا؟</h2></div></div></section>';}
 public static function shortcode_login(): string{return '<div class="avanik-login-inline"><div class="avanik-login-icon">♙</div><h2>ورود به آوانیک</h2><p>برای ادامه نام و شماره موبایل خود را وارد کنید.</p><form class="avanik-login-form"><label><span>نام</span><input type="text" name="first_name"></label><label><span>نام خانوادگی</span><input type="text" name="last_name"></label><label><span>شماره موبایل</span><input type="tel" name="mobile"></label><button type="submit">ادامه</button></form></div>';}
}