<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationDeliveryLog {
 private static function table(): string { global $wpdb; return $wpdb->prefix.'avanik_notification_delivery_log'; }
 public static function register(): void { add_action('init',[self::class,'install']); add_action('avanik_notification_delivery_attempt',[self::class,'attempt'],10,5); add_action('avanik_notification_delivery_result',[self::class,'result'],10,6); }
 public static function install(): void { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::table(); $c=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE {$t} (id bigint unsigned NOT NULL AUTO_INCREMENT,queue_id bigint unsigned NOT NULL,event varchar(80) NOT NULL,role varchar(30) NOT NULL,user_id bigint unsigned NOT NULL DEFAULT 0,channel varchar(30) NOT NULL,provider varchar(80) NOT NULL DEFAULT '',attempt int unsigned NOT NULL DEFAULT 1,status varchar(30) NOT NULL DEFAULT 'attempted',provider_message_id varchar(190) NOT NULL DEFAULT '',error_code varchar(80) NOT NULL DEFAULT '',error_message text NULL,metadata longtext NULL,created_at datetime NOT NULL,PRIMARY KEY(id),KEY queue_id(queue_id),KEY event(event),KEY status(status),KEY channel(channel),KEY created_at(created_at)) {$c};"); }
 public static function attempt(int $queue_id,string $event,string $role,int $user_id,string $channel): void { self::write($queue_id,$event,$role,$user_id,$channel,'','attempted','', '', '', [],1); }
 public static function result(int $queue_id,string $event,string $role,int $user_id,string $channel,string $status,string $provider='',string $provider_message_id='',string $error_code='',string $error_message='',array $metadata=[]): void { self::write($queue_id,$event,$role,$user_id,$channel,$provider,$status,$provider_message_id,$error_code,$error_message,$metadata,0); }
 private static function write(int $qid,string $event,string $role,int $uid,string $channel,string $provider,string $status,string $pmid,string $ecode,string $emsg,array $meta,int $attempt): void { global $wpdb; $wpdb->insert(self::table(),['queue_id'=>$qid,'event'=>sanitize_key($event),'role'=>sanitize_key($role),'user_id'=>absint($uid),'channel'=>sanitize_key($channel),'provider'=>sanitize_text_field($provider),'attempt'=>$attempt,'status'=>sanitize_key($status),'provider_message_id'=>sanitize_text_field($pmid),'error_code'=>sanitize_text_field($ecode),'error_message'=>sanitize_textarea_field($emsg),'metadata'=>wp_json_encode($meta),'created_at'=>current_time('mysql')],['%d','%s','%s','%d','%s','%s','%d','%s','%s','%s','%s','%s']); }
 public static function table_name(): string { return self::table(); }
}