<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationInbox {
 public static function register(): void { add_shortcode('avanik_notifications',[self::class,'shortcode']); add_action('init',[self::class,'install']); add_action('admin_post_avanik_mark_notification_read',[self::class,'mark_read']); add_action('avanik_notification_delivery',[self::class,'capture'],10,2); }
 private static function table(): string { global $wpdb; return $wpdb->prefix.'avanik_notifications'; }
 public static function install(): void { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::table(); $c=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE {$t} (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL,event varchar(80) NOT NULL,title varchar(255) NOT NULL,body text NOT NULL,read_at datetime DEFAULT NULL,created_at datetime NOT NULL,PRIMARY KEY(id),KEY user_id(user_id),KEY read_at(read_at)) {$c};"); }
 public static function capture(string $event,array $payload): void { $uid=(int)($payload['customer_id']??0); if(!$uid)return; global $wpdb; $title='Avanik notification'; $body=NotificationTemplates::render($event,$payload,'fa'); $wpdb->insert(self::table(),['user_id'=>$uid,'event'=>sanitize_key($event),'title'=>$title,'body'=>$body,'created_at'=>current_time('mysql')],['%d','%s','%s','%s','%s']); }
 public static function shortcode(): string { if(!is_user_logged_in())return '<p>Please log in.</p>'; global $wpdb; $rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table().' WHERE user_id=%d ORDER BY id DESC LIMIT 50',get_current_user_id()),ARRAY_A); ob_start(); echo '<div class="avanik-notification-inbox">'; foreach($rows as $r){echo '<article class="'.($r['read_at']?'read':'unread').'" data-id="'.(int)$r['id'].'"><h3>'.esc_html($r['title']).'</h3><div>'.nl2br(esc_html($r['body'])).'</div><small>'.esc_html($r['created_at']).'</small>'; if(!$r['read_at'])echo ' <a href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=avanik_mark_notification_read&id='.(int)$r['id']),'avanik_mark_notification_read')).'">Mark read</a>'; echo '</article>';} echo '</div>'; return ob_get_clean(); }
 public static function mark_read(): void { if(!is_user_logged_in())wp_die('Forbidden',403); check_admin_referer('avanik_mark_notification_read'); $id=absint($_GET['id']??0); global $wpdb; if($id)$wpdb->query($wpdb->prepare('UPDATE '.self::table().' SET read_at=%s WHERE id=%d AND user_id=%d',current_time('mysql'),$id,get_current_user_id())); wp_safe_redirect(wp_get_referer()?:home_url('/')); exit; }
}