<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationCenter {
 private const OPT='avanik_notification_settings'; private const MAX_ATTEMPTS=5;
 public static function register(): void { add_action('admin_menu',[self::class,'menu']); add_action('admin_post_avanik_save_notifications',[self::class,'save']); add_action('admin_post_avanik_retry_notification',[self::class,'retry']); add_action('avanik_refund_notification_queued',[self::class,'queue_refund'],10,4); add_action('avanik_notification_worker',[self::class,'worker']); if(!wp_next_scheduled('avanik_notification_worker'))wp_schedule_event(time()+60,'avanik_minute',[self::class,'worker']); add_filter('cron_schedules',[self::class,'cron']); }
 public static function cron(array $s): array { if(!isset($s['avanik_minute']))$s['avanik_minute']=['interval'=>60,'display'=>'Avanik every minute']; return $s; }
 public static function defaults(): array { return ['email'=>['enabled'=>true,'customer'=>true,'agency'=>false,'admin'=>false],'sms'=>['enabled'=>false,'customer'=>false,'agency'=>false,'admin'=>false],'whatsapp'=>['enabled'=>false,'customer'=>false,'agency'=>false,'admin'=>false],'internal'=>['enabled'=>true,'customer'=>true,'agency'=>true,'admin'=>true]]; }
 public static function settings(): array { return wp_parse_args((array)get_option(self::OPT,[]),self::defaults()); }
 public static function menu(): void { add_submenu_page('avanik-notification-dashboard','تنظیمات ارسال اعلان','تنظیمات ارسال','manage_options','avanik-notifications',[self::class,'page']); }
 public static function page(): void { if(!current_user_can('manage_options'))return; $s=self::settings(); $rows=self::queue_rows(); echo '<div class="wrap av-admin-wrap" dir="rtl"><div class="av-admin-panel-title"><span class="dashicons dashicons-email-alt"></span><div><h1>تنظیمات ارسال اعلان</h1><p>کانال‌های ایمیل، پیامک، واتساپ و اعلان داخلی را کنترل کنید.</p></div></div><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="avanik_save_notifications">'.wp_nonce_field('avanik_save_notifications','_wpnonce',true,false).'<div class="av-admin-card"><table class="widefat striped"><thead><tr><th>کانال</th><th>فعال</th><th>مشتری</th><th>آژانس</th><th>مدیر</th></tr></thead><tbody>'; foreach($s as $channel=>$v){$labels=['email'=>'ایمیل','sms'=>'پیامک','whatsapp'=>'واتساپ','internal'=>'اعلان داخلی'];echo '<tr><td>'.esc_html($labels[$channel]??$channel).'</td>'; foreach(['enabled','customer','agency','admin'] as $k){echo '<td><input type="checkbox" name="n['.esc_attr($channel).']['.$k.']" value="1" '.checked(!empty($v[$k]),true,false).'></td>';} echo '</tr>';} echo '</tbody></table><p><button class="button button-primary">ذخیره تنظیمات</button></p></div></form><div class="av-admin-card"><h2>صف اعلان‌ها</h2><table class="widefat striped"><thead><tr><th>شناسه</th><th>رویداد</th><th>نقش</th><th>کاربر</th><th>کانال</th><th>وضعیت</th><th>تلاش</th><th>آخرین بروزرسانی</th><th>عملیات</th></tr></thead><tbody>'; foreach($rows as $r){$labels=['queued'=>'در صف','retry'=>'تلاش مجدد','failed'=>'ناموفق','dead'=>'متوقف‌شده','sent'=>'ارسال شد','email'=>'ایمیل','sms'=>'پیامک','whatsapp'=>'واتساپ','internal'=>'اعلان داخلی','customer'=>'مشتری','agency'=>'آژانس','admin'=>'مدیر'];$status=$labels[$r['status']]??$r['status'];$channel=$labels[$r['channel']]??$r['channel'];$role=$labels[$r['role']??'']??($r['role']??'');echo '<tr><td>'.(int)$r['id'].'</td><td>'.esc_html($r['event']).'</td><td>'.esc_html($role).'</td><td>'.(int)($r['user_id']??0).'</td><td>'.esc_html($channel).'</td><td>'.esc_html($status).'</td><td>'.(int)$r['attempts'].'/'.self::MAX_ATTEMPTS.'</td><td>'.esc_html($r['updated_at']).'</td><td>'.($r['status']==='failed'||$r['status']==='dead'?'<a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=avanik_retry_notification&id='.(int)$r['id']),'avanik_retry_notification')).'">تلاش دوباره</a>':'').'</td></tr>';} echo '</tbody></table></div></div>'; }
 public static function save(): void { if(!current_user_can('manage_options'))wp_die('دسترسی غیرمجاز',403); check_admin_referer('avanik_save_notifications'); $s=self::defaults(); $in=(array)($_POST['n']??[]); foreach($s as $channel=>$v)foreach($v as $k=>$_)$s[$channel][$k]=!empty($in[$channel][$k]); update_option(self::OPT,$s,false); wp_safe_redirect(admin_url('admin.php?page=avanik-notifications&updated=1')); exit; }
 public static function queue_refund(string $refund_id,string $status,string $booking_id,int $customer_id=0): void { self::enqueue('refund_status',['refund_id'=>$refund_id,'status'=>$status,'booking_id'=>$booking_id,'customer_id'=>$customer_id]); }
 public static function enqueue(string $event,array $payload): void { $recipients=apply_filters('avanik_notification_recipients',[], $event,$payload); if(!$recipients){self::enqueue_legacy($event,$payload);return;} foreach($recipients as $role=>$recipient){$uid=absint($recipient['user_id']??0); foreach((array)($recipient['channels']??[]) as $channel=>$enabled)if($enabled && self::channel_enabled($channel,$role))self::insert($event,$payload,$role,$uid,$channel); } }
 private static function enqueue_legacy(string $event,array $payload): void { self::insert($event,$payload,'customer',absint($payload['customer_id']??0),'email'); }
 private static function channel_enabled(string $channel,string $role): bool { $s=self::settings(); return !empty($s[$channel]['enabled']) && !empty($s[$channel][$role]); }
 private static function insert(string $event,array $payload,string $role,int $uid,string $channel): void { global $wpdb; $wpdb->insert(self::table(),['event'=>$event,'payload'=>wp_json_encode($payload),'status'=>'queued','attempts'=>0,'last_error'=>'','role'=>$role,'user_id'=>$uid,'channel'=>$channel,'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')],['%s','%s','%s','%d','%s','%s','%s','%s','%s']); }
 public static function worker(): void { if(defined('DOING_CRON')&&!DOING_CRON)return; global $wpdb; $now=current_time('mysql'); $rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.self::table().' WHERE (status=%s OR status=%s) AND updated_at<=%s ORDER BY id ASC LIMIT 20','queued','retry',$now),ARRAY_A); foreach($rows as $r)self::process($r); }
 private static function process(array $r): void { global $wpdb; $payload=json_decode((string)$r['payload'],true); do_action('avanik_notification_delivery_attempt',(int)$r['id'],(string)$r['event'],(string)$r['role'],(int)$r['user_id'],(string)$r['channel']); $ok=is_array($payload)&&self::deliver($r['event'],$payload,(string)$r['channel'],(int)$r['user_id']); if($ok){ do_action('avanik_notification_delivery_result',(int)$r['id'],(string)$r['event'],(string)$r['role'],(int)$r['user_id'],(string)$r['channel'],'sent','core','', '', '',[]); $wpdb->update(self::table(),['status'=>'sent','updated_at'=>current_time('mysql')],['id'=>(int)$r['id']],['%s','%s'],['%d']);return;} $attempt=(int)$r['attempts']+1; if($attempt>=self::MAX_ATTEMPTS){$status='dead';$next=current_time('mysql');}else{$status='retry';$delay=min(3600,60*(2**($attempt-1)));$next=date('Y-m-d H:i:s',current_time('timestamp')+$delay);} do_action('avanik_notification_delivery_result',(int)$r['id'],(string)$r['event'],(string)$r['role'],(int)$r['user_id'],(string)$r['channel'],$status,'core','','DELIVERY_FAILED','Delivery failed',[]); $wpdb->update(self::table(),['status'=>$status,'attempts'=>$attempt,'last_error'=>'Delivery failed','updated_at'=>$next],['id'=>(int)$r['id']],['%s','%d','%s','%s'],['%d']); }
 private static function deliver(string $event,array $payload,string $channel,int $uid): bool { if($channel==='internal'){do_action('avanik_notification_delivery',$event,$payload,$channel,$uid);return true;} $provider=(string)apply_filters('avanik_notification_provider_for_channel','core',$channel,$event,$payload,$uid); if($provider!==''&&$provider!=='core'&&NotificationProviderHealth::is_disabled($provider,$channel)){do_action('avanik_notification_delivery_blocked',$event,$payload,$channel,$uid,$provider,'circuit_open');return false;} if($channel==='email'&&$uid){$u=get_userdata($uid);if($u&&is_email($u->user_email))return wp_mail($u->user_email,'Avanik '.sanitize_text_field($event),self::message($event,$payload,$u));return false;} do_action('avanik_notification_delivery',$event,$payload,$channel,$uid); return true; }
 private static function message(string $event,array $payload,$u): string { $locale=get_user_locale($u); $locale=str_starts_with($locale,'en_')?'en':'fa'; return NotificationTemplates::render($event,$payload,$locale); }
 public static function retry(): void { if(!current_user_can('manage_options'))wp_die('دسترسی غیرمجاز',403); check_admin_referer('avanik_retry_notification'); $id=absint($_GET['id']??0); global $wpdb; if($id)$wpdb->update(self::table(),['status'=>'queued','attempts'=>0,'last_error'=>'','updated_at'=>current_time('mysql')],['id'=>$id],['%s','%d','%s','%s'],['%d']); wp_safe_redirect(admin_url('admin.php?page=avanik-notifications')); exit; }
 private static function queue_rows(): array { global $wpdb; return $wpdb->get_results('SELECT id,event,status,attempts,updated_at,role,user_id,channel FROM '.self::table().' ORDER BY id DESC LIMIT 50',ARRAY_A); }
 private static function table(): string { global $wpdb; return $wpdb->prefix.'avanik_notification_queue'; }
 public static function install(): void { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::table(); $c=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE {$t} (id bigint unsigned NOT NULL AUTO_INCREMENT,event varchar(80) NOT NULL,payload longtext NOT NULL,status varchar(20) NOT NULL DEFAULT 'queued',attempts smallint unsigned NOT NULL DEFAULT 0,last_error text NULL,role varchar(30) NOT NULL DEFAULT 'customer',user_id bigint unsigned NOT NULL DEFAULT 0,channel varchar(30) NOT NULL DEFAULT 'email',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),KEY status(status),KEY event(event),KEY updated_at(updated_at),KEY user_channel(user_id,channel)) {$c};"); }
}
