<?php
namespace Avanik;
defined('ABSPATH') || exit;

final class NotificationProviderHealthSlaRiskPolicyAuditNotificationDeliveryHealthAlertEscalationDeliveryReliabilityTrendHealthActionAuditExportVerificationReportScheduleHealthIncidentEscalationNotificationDeliveryHealthSlaTrendAlertAcknowledgementSlaBreachActionRecoveryIncidentOwnershipValidationRepairVerificationClosureSummaryClosureAuditIntegrityDriftIncidentOwnershipAssignmentReviewEscalationAcknowledgementEscalationPolicyAuditVerificationEvidenceRetentionExpiryCheckPostExpiryActionReviewDecisionExecutionGuardAuthorizationAuditChangeAlertAcknowledgementAcknowledgeActionVerificationAuditReviewDecisionVerificationClosureReadinessClosureAuthorizationClosureExecutionGuardManualApprovalVerificationExecutionUnlockGuardReleaseGuardReleaseVerificationGuardReleaseApprovalVerificationGuardReleaseAuditGuardReleaseAuditVerificationGuardReleaseDecisionGuardReleaseDecisionVerificationGuardReleaseDecisionAuditGuardReleaseDecisionAuditVerificationGuardReleaseFinalDecisionGuardReleaseFinalDecisionVerificationGuardReleaseFinalDecisionAuditGuardReleaseFinalDecisionAuditVerification {
    private const OPTION='avanik_sla_drift_guard_release_final_decision_audit_verification';
    private const CAPABILITY='manage_options';
    public static function register(): void { add_options_page('SLA Drift Guard Final Decision Audit Verification','SLA Drift Guard Final Decision Audit Verification',self::CAPABILITY,'avanik-sla-drift-guard-final-decision-audit-verification',[self::class,'render']); }
    public static function evaluate(): array {
        $a=get_option('avanik_sla_drift_guard_release_final_decision_audit',[]); $a=is_array($a)?$a:[];
        $valid=($a['audit_status']??'')==='verified' && ($a['source_verification']??'')==='verified' && ($a['decision_status']??'')==='ready_for_final_decision' && ($a['decision']??'')==='pending_final_decision' && ($a['guard_release']??true)===false && ($a['execution_allowed']??true)===false;
        $result=['verification_status'=>$valid?'verified':'failed','audit_status'=>(string)($a['audit_status']??'unknown'),'source_verification'=>(string)($a['source_verification']??'failed'),'decision_status'=>(string)($a['decision_status']??'unknown'),'decision'=>(string)($a['decision']??'unknown'),'guard_release'=>false,'execution_allowed'=>false,'event'=>'final_decision_audit_verified','reason'=>$valid?'final_decision_audit_is_consistent_and_locked':'final_decision_audit_is_invalid','verified_at'=>time()];
        update_option(self::OPTION,$result,false); return $result;
    }
    public static function render(): void { if(!current_user_can(self::CAPABILITY)) return; $s=self::evaluate(); echo '<div class="wrap"><h1>SLA Drift Guard Final Decision Audit Verification</h1><p>Phase 177 verifies the Phase 176 audit snapshot before any final outcome can be considered.</p><table class="widefat striped"><tbody>'; foreach(['Verification status'=>strtoupper($s['verification_status']),'Audit status'=>strtoupper($s['audit_status']),'Source verification'=>strtoupper($s['source_verification']),'Decision status'=>strtoupper(str_replace('_',' ',$s['decision_status'])),'Decision'=>strtoupper(str_replace('_',' ',$s['decision'])),'Event'=>str_replace('_',' ',$s['event']),'Guard release'=>$s['guard_release']?'YES':'NO','Execution allowed'=>$s['execution_allowed']?'YES':'NO','Reason'=>str_replace('_',' ',$s['reason']),'Verified at'=>wp_date('Y-m-d H:i:s',$s['verified_at'])] as $k=>$v) echo '<tr><th>'.esc_html($k).'</th><td>'.esc_html((string)$v).'</td></tr>'; echo '</tbody></table></div>'; }
}
