<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationPreferences {
 private const OPT='avanik_notification_preferences';
 private const EVENTS=['booking_created'=>'Booking Created','booking_confirmed'=>'Booking Confirmed','booking_cancelled'=>'Booking Cancelled','ticket_issued'=>'Ticket Issued','refund_status'=>'Refund Status','payment_status'=>'Payment Status'];
 public static function register(): void { add_shortcode('avanik_notification_preferences',[self::class,'shortcode']); add_action('admin_post_avanik_save_notification_preferences',[self::class,'save']); add_filter('avanik_notification_recipients',[self::class,'recipients'],10,3); }
 private static function defaults(): array { return ['email'=>true,'sms'=>false,'whatsapp'=>false,'internal'=>true]; }
 public static function get(int $user_id): array { $stored=(array)get_user_meta($user_id,self::OPT,true); return wp_parse_args($stored,self::defaults()); }
 public static function enabled(int $user_id,string $channel): bool { $p=self::get($user_id); return !empty($p[$channel]); }
 public static function event_preferences(int $user_id): array { $p=self::get($user_id); $events=(array)($p['events']??[]); $out=[]; foreach(self::EVENTS as $event=>$label){$out[$event]=wp_parse_args((array)($events[$event]??[]),self::defaults());} return $out; }
 public static function event_enabled(int $user_id,string $event,string $channel): bool { $p=self::event_preferences($user_id); if(isset($p[$event][$channel]))return !empty($p[$event][$channel]); return self::enabled($user_id,$channel); }
 public static function recipients(string $event,array $payload,array $context=[]): array { $out=[]; foreach(['customer_id'=>'customer','agency_id'=>'agency','admin_id'=>'admin'] as $key=>$role){$uid=absint($payload[$key]??$context[$key]??0); if(!$uid||!self::role_allowed($event,$role))continue; $channels=self::get($uid); foreach(array_keys(self::defaults()) as $channel)$channels[$channel]=self::event_enabled($uid,$event,$channel); $out[$role]=['user_id'=>$uid,'channels'=>$channels];} return $out; }
 private static function role_allowed(string $event,string $role): bool { return (bool)apply_filters('avanik_notification_role_allowed',true,$event,$role); }
 public static function shortcode(): string { if(!is_user_logged_in())return '<p>Please log in.</p>'; $p=self::get(get_current_user_id()); $events=self::event_preferences(get_current_user_id()); ob_start(); echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="avanik_save_notification_preferences">'.wp_nonce_field('avanik_save_notification_preferences','_wpnonce',true,false).'<h3>Notification Preferences</h3><h4>Default channels</h4>'; foreach(self::defaults() as $channel=>$enabled){echo '<p><label><input type="checkbox" name="p['.esc_attr($channel).']" value="1" '.checked(!empty($p[$channel]),true,false).'> '.esc_html(ucfirst($channel)).'</label></p>';} echo '<h4>Event preferences</h4><table><thead><tr><th>Event</th><th>Email</th><th>Internal</th><th>SMS</th><th>WhatsApp</th></tr></thead><tbody>'; foreach($events as $event=>$channels){echo '<tr><td>'.esc_html(self::EVENTS[$event]).'</td>'; foreach(self::defaults() as $channel=>$default){echo '<td><input type="checkbox" name="events['.esc_attr($event).']['.esc_attr($channel).']" value="1" '.checked(!empty($channels[$channel]),true,false).'></td>';} echo '</tr>';} echo '</tbody></table><p><button class="button">Save</button></p></form>'; return ob_get_clean(); }
 public static function save(): void { if(!is_user_logged_in())wp_die('Forbidden',403); check_admin_referer('avanik_save_notification_preferences'); $base=self::defaults(); $in=(array)($_POST['p']??[]); foreach($base as $k=>$_)$base[$k]=!empty($in[$k]); $events=[];$posted=(array)($_POST['events']??[]); foreach(self::EVENTS as $event=>$_label){$events[$event]=[]; foreach(self::defaults() as $channel=>$_default)$events[$event][$channel]=!empty($posted[$event][$channel]);} $base['events']=$events; update_user_meta(get_current_user_id(),self::OPT,$base); wp_safe_redirect(wp_get_referer()?:home_url('/')); exit; }
}