<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationProviderHealth {
 private static function table(): string { global $wpdb; return $wpdb->prefix.'avanik_notification_provider_health'; }
 public static function register(): void { add_action('init',[self::class,'install']); add_action('avanik_notification_delivery_result',[self::class,'record'],10,11); add_action('admin_menu',[self::class,'menu']); }
 public static function install(): void { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::table(); $c=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE {$t} (id bigint unsigned NOT NULL AUTO_INCREMENT,provider varchar(80) NOT NULL,channel varchar(30) NOT NULL,total_attempts bigint unsigned NOT NULL DEFAULT 0,sent_count bigint unsigned NOT NULL DEFAULT 0,failed_count bigint unsigned NOT NULL DEFAULT 0,consecutive_failures int unsigned NOT NULL DEFAULT 0,last_status varchar(30) NOT NULL DEFAULT '',last_error_code varchar(80) NOT NULL DEFAULT '',last_error_message text NULL,last_message_id varchar(190) NOT NULL DEFAULT '',last_seen datetime DEFAULT NULL,disabled tinyint(1) NOT NULL DEFAULT 0,disabled_reason text NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY provider_channel(provider,channel),KEY disabled(disabled),KEY updated_at(updated_at)) {$c};"); }
 public static function record(int $queue_id,string $event,string $role,int $user_id,string $channel,string $status,string $provider='',string $provider_message_id='',string $error_code='',string $error_message='',array $metadata=[]): void { $provider=sanitize_text_field($provider?:'core'); $channel=sanitize_key($channel); global $wpdb; $t=self::table(); $row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE provider=%s AND channel=%s",$provider,$channel),ARRAY_A); $now=current_time('mysql'); $sent=$status==='sent'?1:0; $failed=in_array($status,['failed','dead','retry'],true)?1:0; if($row){$consecutive=$failed?(int)$row['consecutive_failures']+1:0;$wpdb->update($t,['total_attempts'=>(int)$row['total_attempts']+1,'sent_count'=>(int)$row['sent_count']+$sent,'failed_count'=>(int)$row['failed_count']+$failed,'consecutive_failures'=>$consecutive,'last_status'=>sanitize_key($status),'last_error_code'=>sanitize_text_field($error_code),'last_error_message'=>sanitize_textarea_field($error_message),'last_message_id'=>sanitize_text_field($provider_message_id),'last_seen'=>$now,'updated_at'=>$now],['id'=>(int)$row['id']]);}else{$wpdb->insert($t,['provider'=>$provider,'channel'=>$channel,'total_attempts'=>1,'sent_count'=>$sent,'failed_count'=>$failed,'consecutive_failures'=>$failed,'last_status'=>sanitize_key($status),'last_error_code'=>sanitize_text_field($error_code),'last_error_message'=>sanitize_textarea_field($error_message),'last_message_id'=>sanitize_text_field($provider_message_id),'last_seen'=>$now,'updated_at'=>$now]);} }
 public static function menu(): void { add_submenu_page('options-general.php','Notification Provider Health','Provider Health','manage_options','avanik-notification-health',[self::class,'page']); }
 public static function page(): void { if(!current_user_can('manage_options'))return; global $wpdb; $rows=$wpdb->get_results('SELECT * FROM '.self::table().' ORDER BY disabled DESC, failed_count DESC, provider ASC',ARRAY_A); echo '<div class="wrap"><h1>Notification Provider Health</h1><p>Operational monitoring only. Provider APIs are not assumed.</p><table class="widefat"><thead><tr><th>Provider</th><th>Channel</th><th>Attempts</th><th>Sent</th><th>Failed</th><th>Success %</th><th>Consecutive Failures</th><th>Last Status</th><th>Last Error</th><th>Last Seen</th><th>State</th></tr></thead><tbody>'; foreach($rows as $r){$rate=$r['total_attempts']?round(((int)$r['sent_count']/(int)$r['total_attempts'])*100,1):0;$state=$r['disabled']?'Disabled':'Active';echo '<tr><td>'.esc_html($r['provider']).'</td><td>'.esc_html($r['channel']).'</td><td>'.(int)$r['total_attempts'].'</td><td>'.(int)$r['sent_count'].'</td><td>'.(int)$r['failed_count'].'</td><td>'.esc_html($rate).'%</td><td>'.(int)$r['consecutive_failures'].'</td><td>'.esc_html($r['last_status']).'</td><td>'.esc_html($r['last_error_code'].' '.$r['last_error_message']).'</td><td>'.esc_html($r['last_seen']).'</td><td>'.esc_html($state).'</td></tr>';}echo '</tbody></table></div>'; }
}