<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationProviderSettings {
 private const OPTION='avanik_notification_providers';
 public static function register(): void { add_action('admin_init',[self::class,'settings']); add_action('admin_menu',[self::class,'menu'],45); }
 public static function settings(): void { register_setting('avanik_notification_provider_settings',self::OPTION,['sanitize_callback'=>[self::class,'sanitize']]); }
 public static function get(): array { $v=get_option(self::OPTION,[]); return is_array($v)?$v:[]; }
 public static function sanitize($input): array { $out=[]; foreach((array)$input as $id=>$p){$id=sanitize_key($id); if(!$id||!is_array($p))continue; $channels=[]; foreach((array)($p['channels']??[]) as $ch=>$enabled){$ch=sanitize_key($ch); if(in_array($ch,['email','sms','whatsapp','internal'],true)&&$enabled)$channels[]=$ch;} $out[$id]=['name'=>sanitize_text_field($p['name']??$id),'adapter'=>sanitize_text_field($p['adapter']??''),'enabled'=>empty($p['enabled'])?0:1,'channels'=>array_values(array_unique($channels)),'priority'=>max(1,min(100,absint($p['priority']??50))),'notes'=>sanitize_textarea_field($p['notes']??'')];} return $out; }
 public static function menu(): void { add_submenu_page('avanik-theme-settings','ارائه‌دهندگان اعلان آوانیک','ارائه‌دهندگان اعلان','manage_options','avanik-notification-providers',[self::class,'render']); }
 public static function render(): void { if(!current_user_can('manage_options'))return; $providers=self::get(); if(!$providers)$providers=['default'=>['name'=>'پیش‌فرض / هسته','adapter'=>'core','enabled'=>1,'channels'=>['internal','email'],'priority'=>50,'notes'=>'']]; ?><div class="wrap" dir="rtl"><h1>ارائه‌دهندگان اعلان آوانیک</h1><p>در این بخش Providerهای اعلان و کانال‌های مجاز مدیریت می‌شوند. کلیدهای API و Secretها عمداً در این مرحله ذخیره نمی‌شوند.</p><form method="post" action="options.php"><?php settings_fields('avanik_notification_provider_settings'); ?><table class="widefat striped"><thead><tr><th>شناسه</th><th>نام</th><th>Adapter</th><th>فعال</th><th>کانال‌ها</th><th>اولویت</th><th>یادداشت</th></tr></thead><tbody><?php foreach($providers as $id=>$p){$base=self::OPTION.'['.esc_attr($id).']';echo '<tr><td><code>'.esc_html($id).'</code></td><td><input class="regular-text" name="'.$base.'[name]" value="'.esc_attr($p['name']??$id).'"/></td><td><input class="regular-text" name="'.$base.'[adapter]" value="'.esc_attr($p['adapter']??'').'"/></td><td><input type="checkbox" name="'.$base.'[enabled]" value="1" '.checked(!empty($p['enabled']),true,false).'/></td><td>';foreach(['email'=>'ایمیل','sms'=>'پیامک','whatsapp'=>'واتساپ','internal'=>'اعلان داخلی'] as $ch=>$label){echo '<label style="margin-left:12px"><input type="checkbox" name="'.$base.'[channels]['.$ch.']" value="1" '.checked(in_array($ch,(array)($p['channels']??[]),true),true,false).'/> '.esc_html($label).'</label>';}echo '</td><td><input type="number" min="1" max="100" name="'.$base.'[priority]" value="'.(int)($p['priority']??50).'"/></td><td><textarea name="'.$base.'[notes]" rows="2">'.esc_textarea($p['notes']??'').'</textarea></td></tr>';}?></tbody></table><?php submit_button('ذخیره تنظیمات'); ?></form></div><?php }
 public static function enabled_for(string $provider,string $channel): bool { $p=self::get(); if(isset($p[$provider])) return !empty($p[$provider]['enabled'])&&in_array($channel,(array)$p[$provider]['channels'],true); return $provider==='core'; }
}
