<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationProviderHealthIncident {
 private const OPTION='avanik_provider_health_incidents';
 public static function register(): void { add_action('admin_init',[self::class,'maybe_migrate']); add_filter('avanik_notification_provider_health_alert_record',[self::class,'open_from_alert'],20,2); add_filter('avanik_notification_provider_health_recovery_route',[self::class,'resolve_from_recovery'],20,2); }
 public static function maybe_migrate(): void { if(false===get_option(self::OPTION,false)) add_option(self::OPTION,[],'','no'); }
 public static function open_from_alert(array $alert,array $context=[]): array { self::maybe_migrate(); $provider=(string)($alert['provider']??''); if($provider==='')return $alert; $code=(string)($alert['code']??'provider_health'); $incidents=(array)get_option(self::OPTION,[]); $key=(string)($incidents[$provider]['incident_key']??''); $status=(string)($incidents[$provider]['status']??''); if($key!==''&&$status==='open'){ $incidents[$provider]['last_alert_code']=$code;$incidents[$provider]['last_alert_at']=time();$incidents[$provider]['severity']=(string)($alert['severity']??$incidents[$provider]['severity']); update_option(self::OPTION,$incidents,false); $alert['incident_key']=$key;$alert['incident_status']='open';return $alert; }
  $key='INC-'.gmdate('Ymd').'-'.strtoupper(substr(hash('sha256',$provider.'|'.microtime(true).'|'.wp_rand()),0,12));
  $incidents[$provider]=['incident_key'=>$key,'provider'=>$provider,'status'=>'open','severity'=>(string)($alert['severity']??'warning'),'first_alert_code'=>$code,'last_alert_code'=>$code,'opened_at'=>time(),'last_alert_at'=>time(),'acknowledged_at'=>null,'acknowledged_by'=>0,'resolved_at'=>null]; update_option(self::OPTION,$incidents,false); $alert['incident_key']=$key;$alert['incident_status']='open'; return $alert; }
 public static function resolve_from_recovery(array $recovery,array $context=[]): array { if(empty($recovery['recovered']))return $recovery; self::maybe_migrate(); $provider=(string)($recovery['provider']??''); $incidents=(array)get_option(self::OPTION,[]); if($provider!==''&&!empty($incidents[$provider])&&($incidents[$provider]['status']??'')==='open'){ $incidents[$provider]['status']='resolved';$incidents[$provider]['resolved_at']=time();$recovery['incident_key']=(string)$incidents[$provider]['incident_key'];$recovery['incident_status']='resolved';update_option(self::OPTION,$incidents,false); } return $recovery; }
 public static function acknowledge(string $provider,int $user_id): bool { self::maybe_migrate();$incidents=(array)get_option(self::OPTION,[]);if(empty($incidents[$provider])||($incidents[$provider]['status']??'')!=='open')return false;$incidents[$provider]['acknowledged_at']=time();$incidents[$provider]['acknowledged_by']=absint($user_id);update_option(self::OPTION,$incidents,false);return true; }
 public static function recent(int $limit=50): array { $incidents=(array)get_option(self::OPTION,[]);$rows=array_values($incidents);usort($rows,static fn($a,$b)=>(int)($b['opened_at']??0)<=>(int)($a['opened_at']??0));return array_slice($rows,0,max(1,min(200,$limit))); }
 public static function current(string $provider): array { $incidents=(array)get_option(self::OPTION,[]);return (array)($incidents[$provider]??[]); }
}