<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationCenter {
 private const OPT='avanik_notification_settings';
 public static function register(): void { add_action('admin_menu',[self::class,'menu']); add_action('admin_post_avanik_save_notifications',[self::class,'save']); add_action('avanik_refund_notification_queued',[self::class,'queue_refund'],10,4); }
 public static function defaults(): array { return ['email'=>['enabled'=>true,'customer'=>true,'agency'=>false,'admin'=>false],'sms'=>['enabled'=>false,'customer'=>false,'agency'=>false,'admin'=>false],'whatsapp'=>['enabled'=>false,'customer'=>false,'agency'=>false,'admin'=>false],'internal'=>['enabled'=>true,'customer'=>true,'agency'=>true,'admin'=>true]]; }
 public static function settings(): array { return wp_parse_args((array)get_option(self::OPT,[]),self::defaults()); }
 public static function menu(): void { add_options_page('Avanik Notifications','Avanik Notifications','manage_options','avanik-notifications',[self::class,'page']); }
 public static function page(): void { if(!current_user_can('manage_options'))return; $s=self::settings(); echo '<div class="wrap"><h1>Avanik Notifications</h1><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="avanik_save_notifications">'.wp_nonce_field('avanik_save_notifications','_wpnonce',true,false).'<table class="widefat"><thead><tr><th>Channel</th><th>Enabled</th><th>Customer</th><th>Agency</th><th>Admin</th></tr></thead><tbody>'; foreach($s as $channel=>$v){echo '<tr><td>'.esc_html(ucfirst($channel)).'</td>'; foreach(['enabled','customer','agency','admin'] as $k){echo '<td><input type="checkbox" name="n['.esc_attr($channel).']['.$k.']" value="1" '.checked(!empty($v[$k]),true,false).'></td>';} echo '</tr>';} echo '</tbody></table><p><button class="button button-primary">Save</button></p></form></div>'; }
 public static function save(): void { if(!current_user_can('manage_options'))wp_die('Forbidden',403); check_admin_referer('avanik_save_notifications'); $s=self::defaults(); $in=(array)($_POST['n']??[]); foreach($s as $channel=>$v)foreach($v as $k=>$_)$s[$channel][$k]=!empty($in[$channel][$k]); update_option(self::OPT,$s,false); wp_safe_redirect(admin_url('options-general.php?page=avanik-notifications&updated=1')); exit; }
 public static function queue_refund(string $refund_id,string $status,string $booking_id,int $customer_id=0): void { self::enqueue('refund_status',['refund_id'=>$refund_id,'status'=>$status,'booking_id'=>$booking_id,'customer_id'=>$customer_id]); }
 public static function enqueue(string $event,array $payload): void { global $wpdb; $t=$wpdb->prefix.'avanik_notification_queue'; $wpdb->insert($t,['event'=>$event,'payload'=>wp_json_encode($payload),'status'=>'queued','attempts'=>0,'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')],['%s','%s','%s','%d','%s','%s']); }
 public static function install(): void { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=$wpdb->prefix.'avanik_notification_queue'; $c=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE {$t} (id bigint unsigned NOT NULL AUTO_INCREMENT,event varchar(80) NOT NULL,payload longtext NOT NULL,status varchar(20) NOT NULL DEFAULT 'queued',attempts smallint unsigned NOT NULL DEFAULT 0,last_error text NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),KEY status(status),KEY event(event)) {$c};"); }
}