<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationProviderHealthDashboard {
 public static function register(): void { add_action('admin_menu',[self::class,'menu']); }
 public static function menu(): void { add_submenu_page('options-general.php','Provider Health','Provider Health','manage_options','avanik-provider-health',[self::class,'render']); }
 public static function render(): void {
  if(!current_user_can('manage_options'))return;
  $providers=NotificationProviderSettings::get();$logs=[];
  if(class_exists(NotificationProviderTestLog::class)&&method_exists(NotificationProviderTestLog::class,'recent'))$logs=NotificationProviderTestLog::recent(100);
  $latest=[];foreach((array)$logs as $log){$id=(string)($log['provider']??$log['provider_id']??'');if($id!==''&&!isset($latest[$id]))$latest[$id]=$log;}
  $alerts=class_exists(NotificationProviderHealthAlertLog::class)?NotificationProviderHealthAlertLog::recent(50):[];
  $incidents=class_exists(NotificationProviderHealthIncident::class)?NotificationProviderHealthIncident::recent(50):[];
  $metrics=class_exists(NotificationProviderHealthIncidentMetrics::class)?NotificationProviderHealthIncidentMetrics::metrics():[];
  echo '<div class="wrap" dir="rtl"><h1>سلامت Providerهای اعلان</h1><p>وضعیت تنظیمات، Credentials، تست اتصال، سلامت، Incidentها و Alertهای اخیر Providerها.</p>';
  echo '<div style="display:flex;gap:12px;flex-wrap:wrap;margin:16px 0">';
  $cards=[['Incidentها',(int)($metrics['incident_count']??0)],['باز',(int)($metrics['open_incidents']??0)],['Resolved',(int)($metrics['resolved_incidents']??0)],['میانگین Acknowledge',NotificationProviderHealthIncidentMetrics::format_duration((int)($metrics['avg_acknowledgement_seconds']??0))],['میانگین Resolution',NotificationProviderHealthIncidentMetrics::format_duration((int)($metrics['avg_resolution_seconds']??0))],['Downtime کل',NotificationProviderHealthIncidentMetrics::format_duration((int)($metrics['total_downtime_seconds']??0))]];
  foreach($cards as $card)echo '<div style="min-width:145px;padding:14px;background:#fff;border:1px solid #dcdcde;border-radius:6px"><strong>'.esc_html($card[0]).'</strong><div style="font-size:20px;margin-top:6px">'.esc_html((string)$card[1]).'</div></div>';echo '</div>';
  echo '<table class="widefat striped"><thead><tr><th>Provider</th><th>Channel</th><th>سلامت</th><th>Credentials</th><th>آخرین تست</th><th>زمان پاسخ</th></tr></thead><tbody>';
  foreach($providers as $id=>$p){$id=(string)$id;$log=$latest[$id]??[];$summary=NotificationProviderHealthSummary::summary($id,['last_test'=>$log]);$label=NotificationProviderHealthSummary::status_label($summary['status']);$duration=$summary['duration_ms']!==null?(int)$summary['duration_ms'].' ms':'—';echo '<tr><td><strong>'.esc_html($summary['name']).'</strong><br><code>'.esc_html($id).'</code></td><td>'.esc_html(implode(', ',(array)$summary['channels'])?:'—').'</td><td>'.esc_html($label).'</td><td>'.($summary['credentials']?'✓':'—').'</td><td>'.($log?esc_html((($log['result']??$log['status']??'')==='success')?'موفق':'ناموفق'):'تست نشده').'</td><td>'.esc_html($duration).'</td></tr>';}
  if(!$providers)echo '<tr><td colspan="6">Providerی تعریف نشده است.</td></tr>';echo '</tbody></table>';
  echo '<h2 style="margin-top:24px">Incident History</h2><table class="widefat striped"><thead><tr><th>Incident</th><th>Provider</th><th>Severity</th><th>First Alert</th><th>Status</th><th>Opened</th><th>Resolved</th><th>Acknowledged</th></tr></thead><tbody>';
  foreach($incidents as $incident){$opened=!empty($incident['opened_at'])?wp_date(get_option('date_format').' '.get_option('time_format'),(int)$incident['opened_at']):'—';$resolved=!empty($incident['resolved_at'])?wp_date(get_option('date_format').' '.get_option('time_format'),(int)$incident['resolved_at']):'—';$ack=!empty($incident['acknowledged_at')?'تأیید شده':'باز';echo '<tr><td><code>'.esc_html($incident['incident_key']??'').'</code></td><td>'.esc_html($incident['provider']??'').'</td><td>'.esc_html($incident['severity']??'').'</td><td>'.esc_html($incident['first_alert_code']??'').'</td><td>'.esc_html($incident['status']??'').'</td><td>'.esc_html($opened).'</td><td>'.esc_html($resolved).'</td><td>'.esc_html($ack).'</td></tr>';}
  if(!$incidents)echo '<tr><td colspan="8">Incident ثبت‌شده‌ای وجود ندارد.</td></tr>';echo '</tbody></table>';
  echo '<h2 style="margin-top:24px">Alert History</h2><table class="widefat striped"><thead><tr><th>Provider</th><th>Alert</th><th>Severity</th><th>Message</th><th>Time</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>';
  foreach($alerts as $alert){$time=!empty($alert['timestamp'])?wp_date(get_option('date_format').' '.get_option('time_format'),(int)$alert['timestamp']):'—';$ack=!empty($alert['acknowledged_at']);echo '<tr><td><code>'.esc_html($alert['provider']??'').'</code></td><td>'.esc_html($alert['code']??'').'</td><td>'.esc_html($alert['severity']??'').'</td><td>'.esc_html($alert['message']??'').'</td><td>'.esc_html($time).'</td><td>'.($ack?'تأیید شده':'باز').'</td><td>';if(!$ack&&!empty($alert['dedupe_key'])){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="avanik_ack_provider_health_alert"><input type="hidden" name="dedupe_key" value="'.esc_attr($alert['dedupe_key']).'">'.wp_nonce_field('avanik_ack_provider_health_alert','_wpnonce',true,false).'<button type="submit" class="button button-small">تأیید Alert</button></form>';}else echo '—';echo '</td></tr>';}
  if(!$alerts)echo '<tr><td colspan="7">Alert ثبت‌شده‌ای وجود ندارد.</td></tr>';echo '</tbody></table></div>';
 }
}