<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationProviderHealth {
 private static function table(): string { global $wpdb; return $wpdb->prefix.'avanik_notification_provider_health'; }
 private static function threshold(): int { return max(3,min(50,absint(get_option('avanik_notification_provider_failure_threshold',10)))); }
 public static function register(): void { add_action('init',[self::class,'install']); add_action('avanik_notification_delivery_result',[self::class,'record'],10,11); add_action('admin_menu',[self::class,'menu']); add_action('admin_post_avanik_provider_health_action',[self::class,'action']); }
 public static function install(): void { global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::table(); $c=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE {$t} (id bigint unsigned NOT NULL AUTO_INCREMENT,provider varchar(80) NOT NULL,channel varchar(30) NOT NULL,total_attempts bigint unsigned NOT NULL DEFAULT 0,sent_count bigint unsigned NOT NULL DEFAULT 0,failed_count bigint unsigned NOT NULL DEFAULT 0,consecutive_failures int unsigned NOT NULL DEFAULT 0,last_status varchar(30) NOT NULL DEFAULT '',last_error_code varchar(80) NOT NULL DEFAULT '',last_error_message text NULL,last_message_id varchar(190) NOT NULL DEFAULT '',last_seen datetime DEFAULT NULL,disabled tinyint(1) NOT NULL DEFAULT 0,disabled_reason text NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY provider_channel(provider,channel),KEY disabled(disabled),KEY updated_at(updated_at)) {$c};"); }
 public static function record(int $queue_id,string $event,string $role,int $user_id,string $channel,string $status,string $provider='',string $provider_message_id='',string $error_code='',string $error_message='',array $metadata=[]): void { $provider=sanitize_text_field($provider?:'core'); $channel=sanitize_key($channel); global $wpdb; $t=self::table(); $row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t} WHERE provider=%s AND channel=%s",$provider,$channel),ARRAY_A); $now=current_time('mysql'); $sent=$status==='sent'?1:0; $failed=in_array($status,['failed','dead','retry'],true)?1:0; if($row){$consecutive=$failed?(int)$row['consecutive_failures']+1:0;$disabled=(int)$row['disabled'];$reason=$row['disabled_reason'];if(!$disabled&&$consecutive>=self::threshold()){$disabled=1;$reason='Circuit breaker: consecutive delivery failures reached threshold '.self::threshold();} $wpdb->update($t,['total_attempts'=>(int)$row['total_attempts']+1,'sent_count'=>(int)$row['sent_count']+$sent,'failed_count'=>(int)$row['failed_count']+$failed,'consecutive_failures'=>$consecutive,'last_status'=>sanitize_key($status),'last_error_code'=>sanitize_text_field($error_code),'last_error_message'=>sanitize_textarea_field($error_message),'last_message_id'=>sanitize_text_field($provider_message_id),'last_seen'=>$now,'disabled'=>$disabled,'disabled_reason'=>$reason,'updated_at'=>$now],['id'=>(int)$row['id']]);}else{$disabled=$failed>=self::threshold()?1:0;$wpdb->insert($t,['provider'=>$provider,'channel'=>$channel,'total_attempts'=>1,'sent_count'=>$sent,'failed_count'=>$failed,'consecutive_failures'=>$failed,'last_status'=>sanitize_key($status),'last_error_code'=>sanitize_text_field($error_code),'last_error_message'=>sanitize_textarea_field($error_message),'last_message_id'=>sanitize_text_field($provider_message_id),'last_seen'=>$now,'disabled'=>$disabled,'disabled_reason'=>$disabled?'Circuit breaker threshold reached':'','updated_at'=>$now]);} }
 public static function is_disabled(string $provider,string $channel): bool { global $wpdb; $v=$wpdb->get_var($wpdb->prepare('SELECT disabled FROM '.self::table().' WHERE provider=%s AND channel=%s',$provider,$channel)); return (bool)$v; }
 public static function menu(): void { add_submenu_page('options-general.php','Notification Provider Health','Provider Health','manage_options','avanik-notification-health',[self::class,'page']); }
 public static function action(): void { if(!current_user_can('manage_options'))wp_die('Forbidden',403); check_admin_referer('avanik_provider_health_action'); global $wpdb; $id=absint($_POST['id']??0);$action=sanitize_key($_POST['provider_action']??''); if($id&&in_array($action,['enable','disable','reset'],true)){if($action==='enable')$wpdb->update(self::table(),['disabled'=>0,'disabled_reason'=>'','consecutive_failures'=>0,'updated_at'=>current_time('mysql')],['id'=>$id]);elseif($action==='disable')$wpdb->update(self::table(),['disabled'=>1,'disabled_reason'=>'Manually disabled by administrator','updated_at'=>current_time('mysql')],['id'=>$id]);else$wpdb->update(self::table(),['disabled'=>0,'disabled_reason'=>'','consecutive_failures'=>0,'last_error_code'=>'','last_error_message'=>'','updated_at'=>current_time('mysql')],['id'=>$id]);} wp_safe_redirect(admin_url('options-general.php?page=avanik-notification-health'));exit; }
 public static function page(): void { if(!current_user_can('manage_options'))return; global $wpdb; $rows=$wpdb->get_results('SELECT * FROM '.self::table().' ORDER BY disabled DESC, failed_count DESC, provider ASC',ARRAY_A); echo '<div class="wrap"><h1>Notification Provider Health</h1><p>Failure threshold: '.(int)self::threshold().' consecutive failures. Automatic disabling is a circuit breaker; administrators can override it.</p><table class="widefat"><thead><tr><th>Provider</th><th>Channel</th><th>Attempts</th><th>Sent</th><th>Failed</th><th>Success %</th><th>Consecutive Failures</th><th>Last Status</th><th>Last Error</th><th>Last Seen</th><th>State</th><th>Action</th></tr></thead><tbody>'; foreach($rows as $r){$rate=$r['total_attempts']?round(((int)$r['sent_count']/(int)$r['total_attempts'])*100,1):0;$state=$r['disabled']?'Disabled':'Active';echo '<tr><td>'.esc_html($r['provider']).'</td><td>'.esc_html($r['channel']).'</td><td>'.(int)$r['total_attempts'].'</td><td>'.(int)$r['sent_count'].'</td><td>'.(int)$r['failed_count'].'</td><td>'.esc_html($rate).'%</td><td>'.(int)$r['consecutive_failures'].'</td><td>'.esc_html($r['last_status']).'</td><td>'.esc_html($r['last_error_code'].' '.$r['last_error_message']).'</td><td>'.esc_html($r['last_seen']).'</td><td>'.esc_html($state).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('avanik_provider_health_action','_wpnonce',true,false).'<input type="hidden" name="action" value="avanik_provider_health_action"><input type="hidden" name="id" value="'.(int)$r['id'].'"><select name="provider_action"><option value="reset">Reset</option><option value="enable">Enable</option><option value="disable">Disable</option></select> <button class="button">Apply</button></form></td></tr>'; } echo '</tbody></table></div>'; }
}