<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class RefundSettlement {
 public static function register(): void { add_action('admin_post_avanik_refund_decision',[self::class,'decision']); }
 public static function approve(string $refund_id,int $admin_id): bool { return self::transition($refund_id,'approved',$admin_id); }
 public static function reject(string $refund_id,int $admin_id,string $reason=''): bool { return self::transition($refund_id,'rejected',$admin_id,$reason); }
 public static function mark_processing(string $refund_id,int $admin_id): bool { return self::transition($refund_id,'processing',$admin_id); }
 public static function complete(string $refund_id,int $admin_id,string $reference): bool { return self::transition($refund_id,'completed',$admin_id,$reference); }
 private static function transition(string $id,string $status,int $actor,string $note=''): bool { global $wpdb; if(!current_user_can('manage_options'))return false; $allowed=['requested'=>['approved','rejected'],'approved'=>['processing','rejected'],'processing'=>['completed','rejected']]; $row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.RefundRepository::table_name().' WHERE refund_id=%s',$id),ARRAY_A); if(!$row||!in_array($status,$allowed[$row['status']]??[],true))return false; $key='refund:'.$id.':'.$status; if(!RefundIdempotency::claim($id,$key))return false; $data=['status'=>$status,'updated_at'=>current_time('mysql')]; if($status==='completed')$data['completed_at']=current_time('mysql'); if($note!=='')$data['reason']=sanitize_text_field($note); $ok=false!==$wpdb->update(RefundRepository::table_name(),$data,['refund_id'=>$id]); if(!$ok)return false; RefundAuditLog::record($id,$actor,$status,$note); RefundNotifications::notify($id,$status,$row['booking_id']); if($status==='completed')AgencyCommissionReversal::reverse($id,$row['booking_id'],(float)$row['avanik_fee']); return true; }
 public static function decision(): void { if(!current_user_can('manage_options'))wp_die('Forbidden',403); check_admin_referer('avanik_refund_decision'); $id=sanitize_text_field(wp_unslash($_POST['refund_id']??'')); $action=sanitize_key(wp_unslash($_POST['decision']??'')); $actor=get_current_user_id(); $ok=$action==='approve'?self::approve($id,$actor):($action==='reject'?self::reject($id,$actor,sanitize_text_field(wp_unslash($_POST['reason']??''))):false); wp_safe_redirect(wp_get_referer()?:admin_url('tools.php')); exit; }
}