<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class RefundNotificationDelivery {
 public static function register(): void { add_action('avanik_refund_status_changed',[self::class,'queue'],10,3); add_shortcode('avanik_refund_timeline',[self::class,'timeline']); }
 public static function queue(string $refund_id,string $status,string $booking_id): void { $r=self::refund($refund_id); if(!$r)return; $uid=(int)($r['customer_user_id']??0); if($uid){ $u=get_userdata($uid); if($u && is_email($u->user_email)) wp_mail($u->user_email,'Avanik Refund '.$status,self::message($refund_id,$booking_id,$status)); } do_action('avanik_refund_notification_queued',$refund_id,$status,$booking_id,$uid); }
 private static function refund(string $id): array|false { global $wpdb; return $wpdb->get_row($wpdb->prepare('SELECT * FROM '.RefundRepository::table_name().' WHERE refund_id=%s',$id),ARRAY_A) ?: false; }
 private static function message(string $refund_id,string $booking_id,string $status): string { return "Avanik refund update\nRefund: {$refund_id}\nBooking: {$booking_id}\nStatus: {$status}\nPlease sign in to your Avanik account for details."; }
 public static function timeline(): string { if(!is_user_logged_in())return '<p>Please log in.</p>'; $id=sanitize_text_field(wp_unslash($_GET['refund_id']??'')); if($id==='')return '<p>Refund not specified.</p>'; $r=RefundCustomerStatus::get($id,get_current_user_id()); if(!$r)return '<p>Refund not found.</p>'; global $wpdb; $rows=$wpdb->get_results($wpdb->prepare('SELECT action,note,created_at FROM '.$wpdb->prefix.'avanik_refund_audit WHERE refund_id=%s ORDER BY id ASC',$id),ARRAY_A); ob_start(); echo '<ol class="avanik-refund-timeline">'; foreach($rows as $row){ echo '<li><strong>'.esc_html($row['action']).'</strong> — '.esc_html($row['created_at']); if(!empty($row['note']))echo ' <span>'.esc_html($row['note']).'</span>'; echo '</li>'; } echo '</ol>'; return ob_get_clean(); }
}