<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class BookingManagement {
 public static function register(): void { add_shortcode('avanik_booking_detail',[self::class,'render']); add_action('admin_post_avanik_update_passenger',[self::class,'update_passenger']); }
 private static function get(string $id): ?array { return BookingRepository::find_by_id($id); }
 private static function allowed(array $b): bool { return is_user_logged_in() && ((int)$b['customer_id']===get_current_user_id() || current_user_can('manage_options')); }
 public static function render(): string { if(!is_user_logged_in())return '<p>برای مشاهده رزرو وارد حساب شوید.</p>'; $id=sanitize_text_field(wp_unslash($_GET['booking_id']??'')); $b=self::get($id); if(!$b||!self::allowed($b))return '<p>رزرو پیدا نشد یا دسترسی ندارید.</p>'; ob_start(); ?><section dir="rtl"><h2>جزئیات رزرو #<?php echo esc_html($b['booking_id']); ?></h2><p>وضعیت: <?php echo esc_html($b['status']); ?></p><p>نوع: <?php echo esc_html($b['booking_type']); ?></p><p>مقصد: <?php echo esc_html($b['destination']); ?></p><p>تاریخ سفر: <?php echo esc_html($b['travel_date']); ?></p><p>تعداد: <?php echo esc_html($b['quantity']); ?></p><p>مبلغ: <?php echo esc_html(number_format((float)$b['total_amount'])); ?></p><h3>اطلاعات مسافر</h3><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><?php wp_nonce_field('avanik_update_passenger'); ?><input type="hidden" name="action" value="avanik_update_passenger"><input type="hidden" name="booking_id" value="<?php echo esc_attr($b['booking_id']); ?>"><p><label>نام<br><input required name="passenger_name" value="<?php echo esc_attr($b['passenger_name']); ?>"></label></p><p><label>موبایل<br><input required name="passenger_phone" value="<?php echo esc_attr($b['passenger_phone']); ?>"></label></p><p><label>ایمیل<br><input type="email" name="passenger_email" value="<?php echo esc_attr($b['passenger_email']); ?>"></label></p><button type="submit">ذخیره اطلاعات</button></form></section><?php return (string)ob_get_clean(); }
 public static function update_passenger(): void { if(!is_user_logged_in()||!check_admin_referer('avanik_update_passenger'))wp_die('Unauthorized'); global $wpdb; $id=sanitize_text_field(wp_unslash($_POST['booking_id']??'')); $b=self::get($id); if(!$b||!self::allowed($b))wp_die('Forbidden'); if(in_array($b['status'],['confirmed','cancelled'],true)&&!current_user_can('manage_options'))wp_die('Booking is locked'); $wpdb->update(BookingRepository::table_name(),['passenger_name'=>sanitize_text_field(wp_unslash($_POST['passenger_name']??'')),'passenger_phone'=>sanitize_text_field(wp_unslash($_POST['passenger_phone']??'')),'passenger_email'=>sanitize_email(wp_unslash($_POST['passenger_email']??'')),'updated_at'=>current_time('mysql')],['booking_id'=>$id]); wp_safe_redirect(home_url('/booking/?booking_id='.rawurlencode($id))); exit; }
}