<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationProviderHealthSla {
 private const DEFAULTS=['acknowledgement_seconds'=>900,'resolution_seconds'=>3600,'downtime_seconds'=>3600];
 public static function register(): void { add_filter('avanik_notification_provider_health_sla',[self::class,'evaluate'],10,2); }
 public static function policy(string $provider=''): array { $configured=apply_filters('avanik_notification_provider_health_sla_policy',[], $provider); $configured=is_array($configured)?$configured:[]; $out=self::DEFAULTS; foreach($configured as $k=>$v){if(array_key_exists($k,$out)&&is_numeric($v))$out[$k]=max(0,(int)$v);} return $out; }
 public static function evaluate(string $provider='',array $context=[]): array { $policy=self::policy($provider); $rows=NotificationProviderHealthIncident::recent(200); $now=time(); $breaches=[]; foreach($rows as $row){if($provider!==''&&(string)($row['provider']??'')!==$provider)continue; $opened=(int)($row['opened_at']??0); if(!$opened)continue; $ack=(int)($row['acknowledged_at']??0); $resolved=(int)($row['resolved_at']??0); $ackSeconds=$ack?max(0,$ack-$opened):max(0,$now-$opened); $resolutionSeconds=$resolved?max(0,$resolved-$opened):max(0,$now-$opened); $downtime=$resolutionSeconds; if(!$ack && $policy['acknowledgement_seconds']>0 && $ackSeconds>$policy['acknowledgement_seconds'])$breaches[]=['incident_key'=>(string)($row['incident_key']??''),'provider'=>(string)($row['provider']??''),'type'=>'acknowledgement','threshold_seconds'=>$policy['acknowledgement_seconds'],'actual_seconds'=>$ackSeconds,'status'=>'breached']; if($policy['resolution_seconds']>0&&$resolutionSeconds>$policy['resolution_seconds'])$breaches[]=['incident_key'=>(string)($row['incident_key']??''),'provider'=>(string)($row['provider']??''),'type'=>'resolution','threshold_seconds'=>$policy['resolution_seconds'],'actual_seconds'=>$resolutionSeconds,'status'=>'breached']; if($policy['downtime_seconds']>0&&$downtime>$policy['downtime_seconds'])$breaches[]=['incident_key'=>(string)($row['incident_key']??''),'provider'=>(string)($row['provider']??''),'type'=>'downtime','threshold_seconds'=>$policy['downtime_seconds'],'actual_seconds'=>$downtime,'status'=>'breached']; }
 return ['provider'=>$provider,'policy'=>$policy,'breach_count'=>count($breaches),'breaches'=>$breaches,'generated_at'=>$now]; }
 public static function format_duration(int $seconds): string { $seconds=max(0,$seconds);$h=intdiv($seconds,3600);$m=intdiv($seconds%3600,60);$s=$seconds%60;return $h>0?sprintf('%dh %02dm',$h,$m):sprintf('%dm %02ds',$m,$s); }
}