<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationProviderHealthDashboard {
 public static function register(): void { add_action('admin_menu',[self::class,'menu']); }
 public static function menu(): void { add_submenu_page('options-general.php','Provider Health','Provider Health','manage_options','avanik-provider-health',[self::class,'render']); }
 public static function render(): void {
  if(!current_user_can('manage_options'))return;
  $providers=NotificationProviderSettings::get();$logs=[];
  if(class_exists(NotificationProviderTestLog::class)&&method_exists(NotificationProviderTestLog::class,'recent'))$logs=NotificationProviderTestLog::recent(100);
  $latest=[];foreach((array)$logs as $log){$id=(string)($log['provider']??$log['provider_id']??'');if($id!==''&&!isset($latest[$id]))$latest[$id]=$log;}
  $alerts=class_exists(NotificationProviderHealthAlertLog::class)?NotificationProviderHealthAlertLog::recent(50):[];
  $incidents=class_exists(NotificationProviderHealthIncident::class)?NotificationProviderHealthIncident::recent(50):[];
  $metrics=class_exists(NotificationProviderHealthIncidentMetrics::class)?NotificationProviderHealthIncidentMetrics::metrics():[];
  $sla=class_exists(NotificationProviderHealthSla::class)?NotificationProviderHealthSla::evaluate():['policy'=>[],'breach_count'=>0,'breaches'=>[]];
  $slaRows=class_exists(NotificationProviderHealthSlaReport::class)?NotificationProviderHealthSlaReport::rows():[];
  $delivery=class_exists(NotificationProviderHealthSlaDeliveryAudit::class)?NotificationProviderHealthSlaDeliveryAudit::summary(30):['attempts'=>0,'sent'=>0,'failed'=>0,'pending'=>0,'success_rate'=>0];
  $deliveryRows=class_exists(NotificationProviderHealthSlaDeliveryAudit::class)?NotificationProviderHealthSlaDeliveryAudit::recent(25):[];
  echo '<div class="wrap" dir="rtl"><h1>سلامت Providerهای اعلان</h1><p>وضعیت تنظیمات، Credentials، تست اتصال، سلامت، Incidentها، SLA و Alertهای اخیر Providerها.</p>';
  echo '<div style="display:flex;gap:12px;flex-wrap:wrap;margin:16px 0">';
  $cards=[['Incidentها',(int)($metrics['incident_count']??0)],['باز',(int)($metrics['open_incidents']??0)],['Resolved',(int)($metrics['resolved_incidents']??0)],['میانگین Acknowledge',NotificationProviderHealthIncidentMetrics::format_duration((int)($metrics['avg_acknowledgement_seconds']??0))],['میانگین Resolution',NotificationProviderHealthIncidentMetrics::format_duration((int)($metrics['avg_resolution_seconds']??0))],['Downtime کل',NotificationProviderHealthIncidentMetrics::format_duration((int)($metrics['total_downtime_seconds']??0))],['SLA Breach',(int)($sla['breach_count']??0)],['SLA Notify Success',(string)($delivery['success_rate']??0).'%']];
  foreach($cards as $card)echo '<div style="min-width:145px;padding:14px;background:#fff;border:1px solid #dcdcde;border-radius:6px"><strong>'.esc_html($card[0]).'</strong><div style="font-size:20px;margin-top:6px">'.esc_html((string)$card[1]).'</div></div>';echo '</div>';
  echo '<h2>SLA Policy</h2><table class="widefat striped"><thead><tr><th>Acknowledgement</th><th>Resolution</th><th>Downtime</th></tr></thead><tbody><tr><td>'.esc_html(NotificationProviderHealthSla::format_duration((int)($sla['policy']['acknowledgement_seconds']??0))).'</td><td>'.esc_html(NotificationProviderHealthSla::format_duration((int)($sla['policy']['resolution_seconds']??0))).'</td><td>'.esc_html(NotificationProviderHealthSla::format_duration((int)($sla['policy']['downtime_seconds']??0))).'</td></tr></tbody></table>';
  echo '<h2 style="margin-top:24px">SLA به تفکیک Provider</h2><p>این جدول Policy مؤثر هر Provider، Incidentها و تعداد نقض SLA را نشان می‌دهد. مقدار 0 یعنی آن معیار غیرفعال است.</p><table class="widefat striped"><thead><tr><th>Provider</th><th>Ack SLA</th><th>Resolution SLA</th><th>Downtime SLA</th><th>Incident</th><th>Open</th><th>Downtime</th><th>SLA Breach</th><th>Ack/Res/Down</th></tr></thead><tbody>';
  foreach($slaRows as $row){$p=$row['policy'];$c=$row['breaches'];$trip=(int)$c['acknowledgement'].' / '.(int)$c['resolution'].' / '.(int)$c['downtime'];echo '<tr><td><strong>'.esc_html($row['name']).'</strong><br><code>'.esc_html($row['provider']).'</code></td><td>'.esc_html(NotificationProviderHealthSla::format_duration((int)$p['acknowledgement_seconds'])).'</td><td>'.esc_html(NotificationProviderHealthSla::format_duration((int)$p['resolution_seconds'])).'</td><td>'.esc_html(NotificationProviderHealthSla::format_duration((int)$p['downtime_seconds'])).'</td><td>'.(int)$row['incident_count'].'</td><td>'.(int)$row['open_incidents'].'</td><td>'.esc_html(NotificationProviderHealthIncidentMetrics::format_duration((int)$row['downtime_seconds'])).'</td><td>'.(int)$row['breach_count'].'</td><td>'.esc_html($trip).'</td></tr>';}
  if(!$slaRows)echo '<tr><td colspan="9">Providerی برای گزارش SLA وجود ندارد.</td></tr>';echo '</tbody></table>';
  echo '<table class="widefat striped" style="margin-top:24px"><thead><tr><th>Provider</th><th>Channel</th><th>سلامت</th><th>Credentials</th><th>آخرین تست</th><th>زمان پاسخ</th></tr></thead><tbody>';
  foreach($providers as $id=>$p){$id=(string)$id;$log=$latest[$id]??[];$summary=NotificationProviderHealthSummary::summary($id,['last_test'=>$log]);$label=NotificationProviderHealthSummary::status_label($summary['status']);$duration=$summary['duration_ms']!==null?(int)$summary['duration_ms'].' ms':'—';echo '<tr><td><strong>'.esc_html($summary['name']).'</strong><br><code>'.esc_html($id).'</code></td><td>'.esc_html(implode(', ',(array)$summary['channels'])?:'—').'</td><td>'.esc_html($label).'</td><td>'.($summary['credentials']?'✓':'—').'</td><td>'.($log?esc_html((($log['result']??$log['status']??'')==='success')?'موفق':'ناموفق'):'تست نشده').'</td><td>'.esc_html($duration).'</td></tr>';}
  if(!$providers)echo '<tr><td colspan="6">Providerی تعریف نشده است.</td></tr>';echo '</tbody></table>';
  echo '<h2 style="margin-top:24px">SLA Breaches</h2><table class="widefat striped"><thead><tr><th>Incident</th><th>Provider</th><th>Type</th><th>Threshold</th><th>Actual</th><th>Status</th></tr></thead><tbody>';
  foreach((array)($sla['breaches']??[]) as $breach){echo '<tr><td><code>'.esc_html($breach['incident_key']??'').'</code></td><td>'.esc_html($breach['provider']??'').'</td><td>'.esc_html($breach['type']??'').'</td><td>'.esc_html(NotificationProviderHealthSla::format_duration((int)($breach['threshold_seconds']??0))).'</td><td>'.esc_html(NotificationProviderHealthSla::format_duration((int)($breach['actual_seconds']??0))).'</td><td>'.esc_html($breach['status']??'breached').'</td></tr>';}
  if(empty($sla['breaches']))echo '<tr><td colspan="6">SLA breach ثبت‌شده‌ای وجود ندارد.</td></tr>';echo '</tbody></table>';
  echo '<h2 style="margin-top:24px">SLA Notification Delivery — 30 Days</h2><div style="display:flex;gap:12px;flex-wrap:wrap;margin:12px 0">';
  foreach([['Attempts',(int)$delivery['attempts']],['Sent',(int)$delivery['sent']],['Failed/Dead',(int)$delivery['failed']],['Pending',(int)$delivery['pending']],['Success Rate',(string)$delivery['success_rate'].'%']] as $m)echo '<div style="min-width:135px;padding:12px;background:#fff;border:1px solid #dcdcde;border-radius:6px"><strong>'.esc_html($m[0]).'</strong><div style="font-size:19px;margin-top:5px">'.esc_html((string)$m[1]).'</div></div>';
  echo '</div><table class="widefat striped"><thead><tr><th>ID</th><th>Queue</th><th>Role</th><th>Channel</th><th>Provider</th><th>Status</th><th>Attempt</th><th>Error</th><th>Time</th></tr></thead><tbody>';
  foreach($deliveryRows as $row)echo '<tr><td>'.(int)$row['id'].'</td><td>'.(int)$row['queue_id'].'</td><td>'.esc_html($row['role']).'</td><td>'.esc_html($row['channel']).'</td><td>'.esc_html($row['provider']).'</td><td>'.esc_html($row['status']).'</td><td>'.(int)$row['attempt'].'</td><td>'.esc_html(trim(($row['error_code']??'').' '.($row['error_message']??''))).'</td><td>'.esc_html($row['created_at']).'</td></tr>';
  if(!$deliveryRows)echo '<tr><td colspan="9">رکورد Delivery برای SLA وجود ندارد.</td></tr>';echo '</tbody></table>';
  echo '<h2 style="margin-top:24px">Incident History</h2><table class="widefat striped"><thead><tr><th>Incident</th><th>Provider</th><th>Severity</th><th>First Alert</th><th>Status</th><th>Opened</th><th>Resolved</th><th>Acknowledged</th></tr></thead><tbody>';
  foreach($incidents as $incident){$opened=!empty($incident['opened_at'])?wp_date(get_option('date_format').' '.get_option('time_format'),(int)$incident['opened_at']):'—';$resolved=!empty($incident['resolved_at'])?wp_date(get_option('date_format').' '.get_option('time_format'),(int)$incident['resolved_at']):'—';$ack=!empty($incident['acknowledged_at'])?'تأیید شده':'باز';echo '<tr><td><code>'.esc_html($incident['incident_key']??'').'</code></td><td>'.esc_html($incident['provider']??'').'</td><td>'.esc_html($incident['severity']??'').'</td><td>'.esc_html($incident['first_alert_code']??'').'</td><td>'.esc_html($incident['status']??'').'</td><td>'.esc_html($opened).'</td><td>'.esc_html($resolved).'</td><td>'.esc_html($ack).'</td></tr>';}
  if(!$incidents)echo '<tr><td colspan="8">Incident ثبت‌شده‌ای وجود ندارد.</td></tr>';echo '</tbody></table>';
  echo '<h2 style="margin-top:24px">Alert History</h2><table class="widefat striped"><thead><tr><th>Provider</th><th>Alert</th><th>Severity</th><th>Message</th><th>Time</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>';
  foreach($alerts as $alert){$time=!empty($alert['timestamp'])?wp_date(get_option('date_format').' '.get_option('time_format'),(int)$alert['timestamp']):'—';$ack=!empty($alert['acknowledged_at']);echo '<tr><td><code>'.esc_html($alert['provider']??'').'</code></td><td>'.esc_html($alert['code']??'').'</td><td>'.esc_html($alert['severity']??'').'</td><td>'.esc_html($alert['message']??'').'</td><td>'.esc_html($time).'</td><td>'.($ack?'تأیید شده':'باز').'</td><td>';if(!$ack&&!empty($alert['dedupe_key'])){echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="avanik_ack_provider_health_alert"><input type="hidden" name="dedupe_key" value="'.esc_attr($alert['dedupe_key']).'">'.wp_nonce_field('avanik_ack_provider_health_alert','_wpnonce',true,false).'<button type="submit" class="button button-small">تأیید Alert</button></form>';}else echo '—';echo '</td></tr>';}
  if(!$alerts)echo '<tr><td colspan="7">Alert ثبت‌شده‌ای وجود ندارد.</td></tr>';echo '</tbody></table></div>';
 }
}