<?php
namespace Avanik;
defined('ABSPATH') || exit;
interface NotificationProviderConnectionTestInterface { public function testConnection(array $credentials): array; }
final class NotificationProviderConnectionTest {
 public static function register(): void { add_action('admin_post_avanik_test_provider_connection',[self::class,'handle']); }
 public static function test(string $provider): array { $provider=sanitize_key($provider); $started=microtime(true); if(!$provider)return self::result($provider,false,'invalid_provider','Invalid provider.',$started); $settings=NotificationProviderSettings::get(); if(empty($settings[$provider])||empty($settings[$provider]['enabled']))return self::result($provider,false,'provider_disabled','Provider is disabled or not configured.',$started); if(NotificationProviderHealth::is_disabled($provider,'internal'))return self::result($provider,false,'circuit_open','Provider is blocked by circuit breaker.',$started); $adapter_name=(string)($settings[$provider]['adapter']??''); if($adapter_name===''||$adapter_name==='core')return self::result($provider,false,'no_external_adapter','No external adapter is registered for this provider.',$started); $adapter=NotificationProviderAdapterRegistry::resolve('internal','provider_connection_test',[],0); if(!$adapter||$adapter->provider()!==$provider||!($adapter instanceof NotificationProviderConnectionTestInterface))return self::result($provider,false,'test_not_supported','This provider adapter does not expose a connection test.',$started); $credentials=NotificationCredentialVault::get($provider); if(!$credentials)return self::result($provider,false,'missing_credentials','No credentials are stored for this provider.',$started); try{$result=$adapter->testConnection($credentials);if(!is_array($result))return self::result($provider,false,'invalid_adapter_result','Adapter returned an invalid result.',$started);$ok=!empty($result['ok']);return self::result($provider,$ok,sanitize_key((string)($result['code']??($ok?'ok':'failed'))),(string)($result['message']??($ok?'Connection successful.':'Connection failed.')),$started,$result);}catch(\Throwable $e){return self::result($provider,false,'adapter_exception','Provider connection test failed.',$started);}}
 private static function result(string $provider,bool $ok,string $code,string $message,float $started,array $extra=[]): array { $ms=(int)round((microtime(true)-$started)*1000); NotificationProviderTestLog::record($provider,$ok,$code,$ms); return array_merge(['ok'=>$ok,'code'=>$code,'message'=>$message,'duration_ms'=>$ms],$extra); }
 public static function handle(): void { if(!current_user_can('manage_options'))wp_die('Forbidden',403); $provider=sanitize_key($_POST['provider']??'');check_admin_referer('avanik_test_provider_connection_'.$provider);$result=self::test($provider);$code=sanitize_key((string)($result['code']??($result['ok']?'ok':'failed')));$message=sanitize_text_field((string)($result['message']??($result['ok']?'Connection successful.':'Connection failed.')));$url=admin_url('options-general.php?page=avanik-provider-credentials&test='.($result['ok']?'success':'failed').'&code='.rawurlencode($code).'&message='.rawurlencode($message));wp_safe_redirect($url);exit; }
}
