<?php
namespace Avanik;
defined('ABSPATH') || exit;

final class NotificationProviderHealthSlaRiskPolicyAuditNotificationDeliveryHealthAlertEscalationDeliveryReliabilityTrendHealthActionAuditExportVerificationReportScheduleHealthIncidentEscalationNotificationDeliveryHealthSlaTrendAlertAcknowledgementSlaBreachActionRecoveryIncidentOwnershipValidationRepairVerificationClosureSummaryClosureAuditIntegrityDriftIncidentOwnershipAssignmentReviewEscalationAcknowledgementEscalationPolicyAuditVerificationEvidenceRetentionExpiryCheckPostExpiryActionReviewDecisionExecutionGuardAuthorizationAuditChangeAlertAcknowledgementAcknowledgeActionVerificationAuditReviewDecisionVerificationClosureReadinessClosureAuthorizationClosureExecutionGuardManualApprovalVerificationExecutionUnlockGuardReleaseGuardReleaseVerificationGuardReleaseApprovalVerificationGuardReleaseAuditGuardReleaseAuditVerificationGuardReleaseDecisionGuardReleaseDecisionVerificationGuardReleaseDecisionAuditGuardReleaseDecisionAuditVerificationGuardReleaseFinalDecisionGuardReleaseFinalDecisionVerificationGuardReleaseFinalDecisionAudit {
    private const OPTION='avanik_sla_drift_guard_release_final_decision_audit';
    private const CAPABILITY='manage_options';
    public static function register(): void { add_options_page('SLA Drift Guard Final Decision Audit','SLA Drift Guard Final Decision Audit',self::CAPABILITY,'avanik-sla-drift-guard-final-decision-audit',[self::class,'render']); }
    public static function evaluate(): array {
        $v=get_option('avanik_sla_drift_guard_release_final_decision_verification',[]); $v=is_array($v)?$v:[];
        $valid=($v['verification_status']??'')==='verified' && ($v['decision_status']??'')==='ready_for_final_decision' && ($v['decision']??'')==='pending_final_decision';
        $result=['audit_status'=>$valid?'verified':'blocked','source_verification'=>(string)($v['verification_status']??'failed'),'decision_status'=>(string)($v['decision_status']??'unknown'),'decision'=>(string)($v['decision']??'unknown'),'event'=>'final_decision_readiness_verified','guard_release'=>false,'execution_allowed'=>false,'reason'=>$valid?'final_decision_readiness_verification_is_auditable_and_locked':'final_decision_readiness_verification_not_valid_for_audit','audited_at'=>time()];
        update_option(self::OPTION,$result,false); return $result;
    }
    public static function render(): void { if(!current_user_can(self::CAPABILITY)) return; $s=self::evaluate(); echo '<div class="wrap"><h1>SLA Drift Guard Final Decision Audit</h1><p>Phase 175 records an auditable snapshot of the verified final-decision readiness state without recording a final outcome or enabling execution.</p><table class="widefat striped"><tbody>'; foreach(['Audit status'=>strtoupper($s['audit_status']),'Source verification'=>strtoupper($s['source_verification']),'Decision status'=>strtoupper(str_replace('_',' ',$s['decision_status'])),'Decision'=>strtoupper(str_replace('_',' ',$s['decision'])),'Event'=>str_replace('_',' ',$s['event']),'Guard release'=>$s['guard_release']?'YES':'NO','Execution allowed'=>$s['execution_allowed']?'YES':'NO','Reason'=>str_replace('_',' ',$s['reason']),'Audited at'=>wp_date('Y-m-d H:i:s',$s['audited_at'])] as $k=>$v) echo '<tr><th>'.esc_html($k).'</th><td>'.esc_html((string)$v).'</td></tr>'; echo '</tbody></table></div>'; }
}
