<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationCredentialVault {
 private const OPTION='avanik_notification_provider_credentials'; private const CIPHER='aes-256-gcm'; private const NONCE_LEN=12;
 public static function register(): void { add_action('admin_menu',[self::class,'menu']); add_action('admin_post_avanik_save_provider_credentials',[self::class,'save']); add_action('admin_post_avanik_delete_provider_credentials',[self::class,'delete']); }
 private static function key(): string { $seed=(defined('AUTH_KEY')?AUTH_KEY:'').'|'.(defined('SECURE_AUTH_KEY')?SECURE_AUTH_KEY:''); return hash('sha256',$seed,true); }
 private static function encrypt(array $data): string { if(!function_exists('openssl_encrypt'))return ''; $nonce=random_bytes(self::NONCE_LEN);$tag='';$raw=openssl_encrypt(wp_json_encode($data),self::CIPHER,self::key(),OPENSSL_RAW_DATA,$nonce,$tag);return $raw===false?'':base64_encode($nonce.$tag.$raw); }
 private static function decrypt(string $blob): array { if(!$blob||!function_exists('openssl_decrypt'))return []; $bin=base64_decode($blob,true);if($bin===false||strlen($bin)<self::NONCE_LEN+16)return []; $nonce=substr($bin,0,self::NONCE_LEN);$tag=substr($bin,self::NONCE_LEN,16);$raw=substr($bin,self::NONCE_LEN+16);$json=openssl_decrypt($raw,self::CIPHER,self::key(),OPENSSL_RAW_DATA,$nonce,$tag);$v=is_string($json)?json_decode($json,true):null;return is_array($v)?$v:[]; }
 private static function all(): array { $raw=get_option(self::OPTION,[]);if(!is_array($raw))return []; $out=[];foreach($raw as $id=>$blob)$out[(string)$id]=self::decrypt((string)$blob);return $out; }
 public static function get(string $provider): array { $all=self::all();return isset($all[$provider])&&is_array($all[$provider])?$all[$provider]:[]; }
 public static function has(string $provider): bool { return self::get($provider)!==[]; }
 public static function set(string $provider,array $credentials): bool { $provider=sanitize_key($provider);if(!$provider)return false;$credentials=self::sanitize($credentials);$blob=self::encrypt($credentials);if(!$blob)return false;$raw=get_option(self::OPTION,[]);if(!is_array($raw))$raw=[];$raw[$provider]=$blob;return update_option(self::OPTION,$raw,false); }
 public static function remove(string $provider): bool { $raw=get_option(self::OPTION,[]);if(!is_array($raw)||!array_key_exists($provider,$raw))return false;unset($raw[$provider]);return update_option(self::OPTION,$raw,false); }
 private static function sanitize(array $c): array { $out=[];foreach($c as $k=>$v){$k=sanitize_key($k);if(!$k)continue;if(is_scalar($v))$out[$k]=sanitize_text_field((string)$v);}return $out; }
 public static function menu(): void { add_submenu_page('options-general.php','Provider Credentials','Provider Credentials','manage_options','avanik-provider-credentials',[self::class,'render']); }
 public static function render(): void { if(!current_user_can('manage_options'))return;$providers=NotificationProviderSettings::get();$test=sanitize_key($_GET['test']??'');$message=sanitize_text_field(wp_unslash($_GET['message']??'')); ?><div class="wrap" dir="rtl"><h1>اعتبارات امنیتی Providerها</h1><div class="notice notice-warning"><p>کلیدها و Secretها به‌صورت رمزنگاری‌شده ذخیره می‌شوند و مقدار واقعی Secret بعد از ذخیره مجدداً نمایش داده نمی‌شود. برای تعویض Secret مقدار جدید را وارد کنید.</p></div><?php if($test==='success'): ?><div class="notice notice-success"><p><?php echo esc_html($message?:'اتصال Provider با موفقیت آزمایش شد.'); ?></p></div><?php elseif($test==='failed'): ?><div class="notice notice-error"><p><?php echo esc_html($message?:'آزمایش اتصال Provider ناموفق بود.'); ?></p></div><?php endif; ?><table class="widefat striped"><thead><tr><th>Provider</th><th>Credentials</th><th>Action</th></tr></thead><tbody><?php foreach($providers as $id=>$p){$id=(string)$id;$has=self::has($id);echo '<tr><td><strong>'.esc_html($p['name']??$id).'</strong><br><code>'.esc_html($id).'</code></td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('avanik_save_provider_credentials_'.$id,'_wpnonce',true,false).'<input type="hidden" name="action" value="avanik_save_provider_credentials"><input type="hidden" name="provider" value="'.esc_attr($id).'">';foreach(['api_key','api_secret','token','account_id'] as $field){echo '<label style="display:block;margin:5px 0">'.esc_html($field).': <input type="password" autocomplete="new-password" name="credentials['.esc_attr($field).']" value="" class="regular-text" placeholder="'.($has?'ذخیره شده — برای تغییر وارد کنید':'وارد کنید').'" /></label>';}echo '<p><button class="button button-primary">ذخیره</button></p></form></td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('avanik_delete_provider_credentials_'.$id,'_wpnonce',true,false).'<input type="hidden" name="action" value="avanik_delete_provider_credentials"><input type="hidden" name="provider" value="'.esc_attr($id).'">'.($has?'<button class="button">حذف Credentials</button>':'—').'</form>'.($has?'<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="margin-top:6px">'.wp_nonce_field('avanik_test_provider_connection_'.$id,'_wpnonce',true,false).'<input type="hidden" name="action" value="avanik_test_provider_connection"><input type="hidden" name="provider" value="'.esc_attr($id).'"> <button class="button">تست اتصال</button></form>':'').'</td></tr>';}?></tbody></table></div><?php }
 public static function save(): void { if(!current_user_can('manage_options'))wp_die('Forbidden',403);$provider=sanitize_key($_POST['provider']??'');check_admin_referer('avanik_save_provider_credentials_'.$provider);$credentials=(array)($_POST['credentials']??[]);$credentials=array_filter($credentials,static fn($v)=>$v!==''&&$v!==null);if($credentials)self::set($provider,$credentials);wp_safe_redirect(admin_url('options-general.php?page=avanik-provider-credentials&saved=1'));exit; }
 public static function delete(): void { if(!current_user_can('manage_options'))wp_die('Forbidden',403);$provider=sanitize_key($_POST['provider']??'');check_admin_referer('avanik_delete_provider_credentials_'.$provider);self::remove($provider);wp_safe_redirect(admin_url('options-general.php?page=avanik-provider-credentials&deleted=1'));exit; }
}