<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class NotificationProviderHealthAlertLog {
 private const OPTION='avanik_provider_health_alert_log';
 public static function register(): void { add_action('admin_init',[self::class,'maybe_migrate']); add_filter('avanik_notification_provider_health_alert_record',[self::class,'record'],10,2); }
 public static function maybe_migrate(): void { if(false===get_option(self::OPTION,false))add_option(self::OPTION,[],'','no'); }
 public static function record(array $alert,array $context=[]): array { self::maybe_migrate(); $log=get_option(self::OPTION,[]); if(!is_array($log))$log=[]; $key=(string)($alert['dedupe_key']??''); $now=time(); $last=(array)($log[$key]??[]); $cooldown=max(60,absint($context['cooldown_seconds']??900)); if($key!==''&&$last&&($now-(int)($last['timestamp']??0))<$cooldown){$alert['recorded']=false;$alert['deduplicated']=true;return $alert;} $entry=['provider'=>(string)($alert['provider']??''),'code'=>(string)($alert['code']??''),'severity'=>(string)($alert['severity']??'info'),'message'=>(string)($alert['message']??''),'dedupe_key'=>$key,'timestamp'=>$now,'acknowledged_at'=>null,'acknowledged_by'=>0]; if($key!=='')$log[$key]=$entry; $entries=array_values($log); usort($entries,static fn($a,$b)=>(int)($b['timestamp']??0)<=>(int)($a['timestamp']??0)); $log=[]; foreach(array_slice($entries,0,200)as$e){$k=(string)($e['dedupe_key']??'');if($k!=='')$log[$k]=$e;} update_option(self::OPTION,$log,false); $alert['recorded']=true;$alert['deduplicated']=false;return $alert; }
 public static function acknowledge(string $key,int $user_id): bool { self::maybe_migrate(); $log=get_option(self::OPTION,[]); if(!is_array($log)||!isset($log[$key]))return false; $log[$key]['acknowledged_at']=time();$log[$key]['acknowledged_by']=absint($user_id);update_option(self::OPTION,$log,false);return true; }
 public static function recent(int $limit=50): array { $log=get_option(self::OPTION,[]); if(!is_array($log))return []; $entries=array_values($log); usort($entries,static fn($a,$b)=>(int)($b['timestamp']??0)<=>(int)($a['timestamp']??0)); return array_slice($entries,0,max(1,min(200,$limit))); }
 public static function clear(): void { delete_option(self::OPTION); }
}