<?php
namespace Avanik;
defined('ABSPATH') || exit;
final class RefundSettlement {
 public static function register(): void { add_action('admin_post_avanik_refund_decision',[self::class,'decision']); }
 public static function approve(string $refund_id,int $admin_id): bool { return self::transition($refund_id,'approved',$admin_id); }
 public static function reject(string $refund_id,int $admin_id,string $reason=''): bool { return self::transition($refund_id,'rejected',$admin_id,$reason); }
 public static function mark_processing(string $refund_id,int $admin_id,string $idempotency_key=''): bool { $key=$idempotency_key!==''?$idempotency_key:'refund:'.$refund_id.':processing'; return self::transition($refund_id,'processing',$admin_id,'',$key); }
 public static function complete(string $refund_id,int $admin_id,string $reference,string $idempotency_key=''): bool { $reference=sanitize_text_field($reference); if($reference==='')return false; $key=$idempotency_key!==''?$idempotency_key:'refund:'.$refund_id.':completed:'.hash('sha256',$reference); return self::transition($refund_id,'completed',$admin_id,$reference,$key); }
 public static function execute_gateway(string $refund_id,RefundGatewayInterface $gateway,int $admin_id,string $idempotency_key=''): array|\WP_Error { global $wpdb; if(!current_user_can('manage_options'))return new \WP_Error('forbidden','Forbidden'); $row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.RefundRepository::table_name().' WHERE refund_id=%s',$refund_id),ARRAY_A); if(!$row)return new \WP_Error('not_found','Refund not found'); if($row['status']!=='approved')return new \WP_Error('invalid_status','Refund must be approved before gateway execution'); $key=$idempotency_key!==''?$idempotency_key:'refund:'.$refund_id.':gateway'; if(!RefundIdempotency::claim($refund_id,$key))return new \WP_Error('duplicate','Refund settlement already claimed'); $result=$gateway->execute($row); if(!is_array($result)||empty($result['status']))return new \WP_Error('gateway_error','Invalid refund gateway response'); self::transition_after_gateway($row,$result,$admin_id); return $result; }
 private static function transition_after_gateway(array $row,array $result,int $actor): void { $status=sanitize_key($result['status']); if($status==='processing')self::transition($row['refund_id'],'processing',$actor,(string)($result['reference']??''),'refund:'.$row['refund_id'].':gateway-processing'); elseif($status==='completed'&&!empty($result['reference']))self::complete($row['refund_id'],$actor,(string)$result['reference'],'refund:'.$row['refund_id'].':gateway-completed'); }
 private static function transition(string $id,string $status,int $actor,string $note='',string $key=''): bool { global $wpdb; if(!current_user_can('manage_options'))return false; $allowed=['requested'=>['approved','rejected'],'approved'=>['processing','rejected'],'processing'=>['completed','rejected']]; $row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.RefundRepository::table_name().' WHERE refund_id=%s',$id),ARRAY_A); if(!$row||!in_array($status,$allowed[$row['status']]??[],true))return false; if($key==='')$key='refund:'.$id.':'.$status; if(!RefundIdempotency::claim($id,$key))return false; $data=['status'=>$status,'updated_at'=>current_time('mysql')]; if($status==='completed'){$data['completed_at']=current_time('mysql');$data['provider_reference']=$note;} elseif($note!=='')$data['reason']=$note; $ok=false!==$wpdb->update(RefundRepository::table_name(),$data,['refund_id'=>$id,'status'=>$row['status']]); if(!$ok)return false; RefundAuditLog::record($id,$actor,$status,$note); RefundNotifications::notify($id,$status,$row['booking_id']); if($status==='completed')AgencyCommissionReversal::reverse($id,$row['booking_id'],(float)$row['avanik_fee']); return true; }
 public static function decision(): void { if(!current_user_can('manage_options'))wp_die('Forbidden',403); check_admin_referer('avanik_refund_decision'); $id=sanitize_text_field(wp_unslash($_POST['refund_id']??'')); $action=sanitize_key(wp_unslash($_POST['decision']??'')); $actor=get_current_user_id(); $ok=$action==='approve'?self::approve($id,$actor):($action==='reject'?self::reject($id,$actor,sanitize_text_field(wp_unslash($_POST['reason']??''))):false); wp_safe_redirect(wp_get_referer()?:admin_url('tools.php')); exit; }
}