<?php
defined('ABSPATH') || exit;
require_once __DIR__ . '/inc/Navigation.php';
require_once __DIR__ . '/inc/Theme.php';
require_once __DIR__ . '/inc/Booking.php';
require_once __DIR__ . '/inc/BookingMeta.php';
require_once __DIR__ . '/inc/BookingTemplate.php';
require_once __DIR__ . '/inc/BookingRepository.php';
require_once __DIR__ . '/inc/BookingSchema.php';
require_once __DIR__ . '/inc/BookingLifecycle.php';
require_once __DIR__ . '/inc/BookingService.php';
require_once __DIR__ . '/inc/BookingActions.php';
require_once __DIR__ . '/inc/Payment.php';
require_once __DIR__ . '/inc/PaymentRepository.php';
require_once __DIR__ . '/inc/PaymentSchema.php';
require_once __DIR__ . '/inc/PaymentService.php';
require_once __DIR__ . '/inc/PaymentLifecycle.php';
require_once __DIR__ . '/inc/PaymentGatewayInterface.php';
require_once __DIR__ . '/inc/CardToCardGateway.php';
require_once __DIR__ . '/inc/PaymentSettings.php';
require_once __DIR__ . '/inc/ZarinPalGateway.php';
require_once __DIR__ . '/inc/FlightProviderInterface.php';
require_once __DIR__ . '/inc/FlightOffer.php';
require_once __DIR__ . '/inc/FlightSearchService.php';
require_once __DIR__ . '/inc/NullFlightProvider.php';
require_once __DIR__ . '/inc/ProviderManager.php';
require_once __DIR__ . '/inc/ProviderRepository.php';
require_once __DIR__ . '/inc/Marketplace.php';
require_once __DIR__ . '/inc/MarketplaceSchema.php';
require_once __DIR__ . '/inc/ProviderAdmin.php';
require_once __DIR__ . '/inc/AgencyDashboard.php';
require_once __DIR__ . '/inc/MarketplaceLifecycle.php';
require_once __DIR__ . '/inc/AgencyOnboarding.php';
require_once __DIR__ . '/inc/Inventory.php';
require_once __DIR__ . '/inc/CommissionLedger.php';
require_once __DIR__ . '/inc/Product.php';
require_once __DIR__ . '/inc/ProductRepository.php';
require_once __DIR__ . '/inc/ProductModeration.php';
require_once __DIR__ . '/inc/AgencyProductDashboard.php';
require_once __DIR__ . '/inc/AgencyProductAdmin.php';
require_once __DIR__ . '/inc/AgencyProductList.php';
require_once __DIR__ . '/inc/AgencyProductEditor.php';
require_once __DIR__ . '/inc/ProductTypeFields.php';
require_once __DIR__ . '/inc/ProductMedia.php';
require_once __DIR__ . '/inc/ProductCatalog.php';
require_once __DIR__ . '/inc/ProductDetail.php';
require_once __DIR__ . '/inc/ProductBooking.php';
require_once __DIR__ . '/inc/PaymentCheckout.php';
require_once __DIR__ . '/inc/CardToCardPayment.php';
require_once __DIR__ . '/inc/PaymentAdmin.php';
require_once __DIR__ . '/inc/Availability.php';
require_once __DIR__ . '/inc/BookingAvailability.php';
require_once __DIR__ . '/inc/CustomerBookingDashboard.php';
require_once __DIR__ . '/inc/AgencyBookingDashboard.php';
require_once __DIR__ . '/inc/ModerationAdmin.php';
require_once __DIR__ . '/inc/ModerationFilters.php';
\Avanik\BookingLifecycle::register();
\Avanik\BookingActions::register();
\Avanik\PaymentLifecycle::register();
\Avanik\MarketplaceLifecycle::register();
\Avanik\CommissionLedger::install();
\Avanik\ProductRepository::install();
\Avanik\Availability::install();
\Avanik\AgencyProductDashboard::register();
\Avanik\AgencyProductAdmin::register();
\Avanik\AgencyProductList::register();
\Avanik\AgencyProductEditor::register();
\Avanik\ProductMedia::register();
\Avanik\ProductCatalog::register();
\Avanik\ProductDetail::register();
\Avanik\ProductBooking::register();
\Avanik\PaymentCheckout::register();
\Avanik\CardToCardPayment::register();
\Avanik\PaymentAdmin::register();
\Avanik\PaymentSettings::register();
\Avanik\CustomerBookingDashboard::register();
\Avanik\AgencyBookingDashboard::register();
\Avanik\ModerationAdmin::register();
\Avanik\ModerationFilters::register();
\Avanik\Theme::boot();
