<?php if (!defined('ABSPATH')) exit; ?><!doctype html>
<html <?php language_attributes(); ?> dir="rtl"><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class('avanik-site'); ?>><?php wp_body_open(); ?>
<header class="avanik-header">
<div class="avanik-topbar"><div class="avanik-shell avanik-topbar-inner">
<a class="avanik-top-contact" href="tel:<?php echo esc_attr(avanik_option('phone','021-12345678')); ?>"><span class="avanik-icon">☎</span><?php echo esc_html(avanik_option('phone','021-12345678')); ?></a>
<?php if((int)avanik_option('show_social_header',1)): ?><div class="avanik-header-socials">
<?php foreach([['instagram','اینستاگرام','instagram'],['telegram','تلگرام','telegram'],['whatsapp','واتساپ','whatsapp'],['linkedin','لینکدین','linkedin'],['youtube','یوتیوب','youtube']] as $s): $url=avanik_option($s[0],'#'); if($url && $url!=='#'): ?><a href="<?php echo esc_url($url); ?>" target="_blank" rel="noopener" aria-label="<?php echo esc_attr($s[1]); ?>" class="social-<?php echo esc_attr($s[2]); ?>"><span aria-hidden="true"></span></a><?php endif; endforeach; ?></div><?php endif; ?>
<a class="avanik-login-link" href="<?php echo esc_url(wp_login_url()); ?>" aria-label="ورود یا ثبت نام"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"></circle><path d="M4 21c.7-4.1 3.2-6.2 8-6.2s7.3 2.1 8 6.2"></path></svg></a>
</div></div>
<div class="avanik-nav-wrap"><div class="avanik-shell avanik-nav">
<a class="avanik-brand" href="<?php echo esc_url(home_url('/')); ?>" aria-label="آوانیک پرواز آسیا"><img src="<?php echo esc_url(avanik_option('logo',AVANIK_URI.'/assets/images/avanik-logo.svg')); ?>" alt="آوانیک پرواز آسیا"></a>
<nav class="avanik-main-menu" aria-label="منوی اصلی آوانیک"><?php if(has_nav_menu('primary')){wp_nav_menu(['theme_location'=>'primary','container'=>false,'fallback_cb'=>false,'menu_class'=>'avanik-menu-list']);}else{?><ul class="avanik-menu-list"><li class="current-menu-item"><a href="<?php echo esc_url(home_url('/')); ?>">صفحه اصلی</a></li><li><a href="<?php echo esc_url(home_url('/پروازها/')); ?>">پروازها</a></li><li><a href="<?php echo esc_url(home_url('/تورهای-خارجی/')); ?>">تورهای خارجی</a></li><li><a href="<?php echo esc_url(home_url('/هتل/')); ?>">هتل</a></li><li><a href="<?php echo esc_url(home_url('/ویزای-مسافرتی/')); ?>">ویزای مسافرتی</a></li><li><a href="<?php echo esc_url(home_url('/بلاگ/')); ?>">بلاگ</a></li><li><a href="<?php echo esc_url(home_url('/درباره-ما/')); ?>">درباره ما</a></li><li><a href="<?php echo esc_url(home_url('/تماس-با-ما/')); ?>">تماس با ما</a></li></ul><?php } ?></nav>
<button class="avanik-mobile-toggle" type="button" aria-label="باز کردن منو">☰</button></div></div></header>
